/*

Copyright 2008-2015 Clipperz Srl

This file is part of Clipperz, the online password manager.
For further information about its features and functionalities please
refer to http://www.clipperz.com.

* Clipperz is free software: you can redistribute it and/or modify it
  under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version.

* Clipperz is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Affero General Public License for more details.

* You should have received a copy of the GNU Affero General Public
  License along with Clipperz. If not, see http://www.gnu.org/licenses/.

*/

//
//	normal.js
//	New Image
//
//	Created by Giulio Cesare Solaroli on 2/13/12
//	Copyright 2012 Clipperz
//	This code was generated by Opacity. You may use or modify it in any way.
//

var kClipperz_PM_UI_Canvas_Logo_normalWidth = 150.0;
var kClipperz_PM_UI_Canvas_Logo_normalHeight = 39.0;

function Clipperz_PM_UI_Canvas_Logo_normal(canvas, logo, fontSize, text_color)
{
	var context = canvas.getContext("2d");

	canvas.width = kClipperz_PM_UI_Canvas_Logo_normalWidth;
	canvas.height = kClipperz_PM_UI_Canvas_Logo_normalHeight;

	context.save();
	context.scale(canvas.width / kClipperz_PM_UI_Canvas_Logo_normalWidth, canvas.height / kClipperz_PM_UI_Canvas_Logo_normalHeight);
	context.clearRect(0.0, 0.0, kClipperz_PM_UI_Canvas_Logo_normalWidth, kClipperz_PM_UI_Canvas_Logo_normalHeight);
	
	context.font = fontSize + " HelveticaNeue-Bold";
	context.fillStyle = text_color;
	context.fillText(logo, 3, 30);
	
	context.restore();
}
