application: clipperz
version: 1
runtime: python
api_version: 1

handlers:
- url: /json
  script: clipperz.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: clipperz.py
