/*

Copyright 2008-2015 Clipperz Srl

This file is part of Clipperz, the online password manager.
For further information about its features and functionalities please
refer to http://www.clipperz.com.

* Clipperz is free software: you can redistribute it and/or modify it
  under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version.

* Clipperz is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Affero General Public License for more details.

* You should have received a copy of the GNU Affero General Public
  License along with Clipperz. If not, see http://www.gnu.org/licenses/.

*/

Clipperz.PM.Strings.Languages['it-IT'.toLowerCase()] = MochiKit.Base.merge(Clipperz.PM.Strings.Languages['en-us'], {
'clipperzServiceDescription':	"<h2>Tienilo per te!</h2> <ul> <li> <h3>Clipperz è:</h3> <ul> <li> <p>un archivio semplice e sicuro per le tue password</p> </li> <li> <p>un canale di accesso unificato a tutti i tuoi servizi online</p> </li> <li> <p>una cassaforte digitale per tutti i tuoi dati riservati</p> </li> </ul> </li> <li> <h3>Con Clipperz puoi:</h3> <ul> <li> <p>memorizzare e gestire le password e le credenziali di accesso dei tuoi servizi online</p> </li> <li> <p>accedere ai tuoi servizi online con un solo click senza bisogno di inserire username o password</p> </li> <li> <p>proteggere tutte le tue informazioni confidenziali: codice dell&#x27;allarme di casa, dati delle carte di credito, …</p> </li> <li> <p>condividere dati riservati con i tuoi familiari o colleghi (disponibile a breve)</p> </li> </ul> </li> <li> <h3>I vantaggi di Clipperz:</h3> <ul> <li> <p>gratuito e completamente anonimo</p> </li> <li> <p>accessibile da qualsiasi computer</p> </li> <li> <p>nessun software da scaricare e niente da installare</p> </li> <li> <p>mai più informazioni riservate sul tuo PC o sulla carta!</p> </li> </ul> </li> <li> <h3>La sicurezza di Clipperz:</h3> <ul> <li> <p>i dati sono criptati dal tuo browser prima di essere inviati a Clipperz</p> </li> <li> <p>la chiave per decriptare i dati è conosciuta soltanto da te</p> </li> <li> <p>Clipperz riceve e memorizza solo i tuoi dati criptati e non ha nessuna possibilità di accedere alla versione in chiaro</p> </li> <li> <p>Clipperz utilizza solo sistemi crittografici standard, senza nessuna velleità di inventare e proporre nuovi algoritmi non validati dalla comunità scientifica</p> </li> <li> <p>tutto il codice di Clipperz è disponibile e può essere analizzato in qualsiasi momento, ma non serve essere un esperto di crittografia per apprezzare la sicurezza e la comodità di Clipperz!</p> </li> </ul> </li> <li><a href=\"http://www.clipperz.com\" target=\"_blank\">Maggiori informazioni su Clipperz (in inglese)</a> </li> </ul> ",
'loginFormTitle':	"accedi a Clipperz",
'loginFormUsernameLabel':	"Utente",
'loginFormPassphraseLabel':	"frase segreta",
'loginFormDontHaveAnAccountLabel':	"non ti sei ancora registrato?",
'loginFormCreateOneLabel':	"registrati adesso",
'loginFormForgotYourCredentialsLabel':	"hai perso i dati di accesso?",
'loginFormAarghThatsBadLabel':	"aargh! questo non è bello!",
'loginFormAfraidOfMaliciousScriptsLabel':	"non ti fidi?",
'loginFormVerifyTheCodeLabel':	"controlla il codice",
'loginFormButtonLabel':	"Accedi",
'loginFormOneTimePasswordCheckboxLabel':	"usa un codice “usa e getta”",
'loginFormOneTimePasswordCheckboxDescription':	"",
'loginPanelSwithLanguageDescription':	"<h5>Seleziona la tua lingua preferita</h5> ",
'browserCompatibilityDescription':	"<p>Clipperz consiglia Firefox per una maggiore sicurezza. Clipperz supporta anche Opera ed Internet Explorer.</p> ",
'OTPloginMessagePanelInitialTitle':	"Accesso con codice “usa e getta”",
'OTPloginMessagePanelInitialText':	"Invio delle credenziali OTP ...",
'OTPloginMessagePanelLoadingTitle':	"Accesso con codice “usa e getta”",
'OTPloginMessagePanelLoadingText':	"Caricamento dei dati di autenticazione criptati ...",
'OTPloginMessagePanelProcessingTitle':	"Accesso con codice “usa e getta”",
'OTPloginMessagePanelProcessingText':	"Decodifica locale dei dati di autenticazione ...",
'loginMessagePanelInitialTitle':	"Connessione in corso ...",
'loginMessagePanelInitialText':	"---",
'loginMessagePanelInitialButtonLabel':	"Annulla",
'loginMessagePanelConnectedTitle':	"Connesso",
'loginMessagePanelConnectedText':	"Fatto",
'loginMessagePanelFailureTitle':	"Errore",
'loginMessagePanelFailureText':	"Connessione fallita",
'loginMessagePanelFailureButtonLabel':	"Chiudi",
'connectionLoginSendingCredentialsMessageTitle':	"Verifica delle credenziali",
'connectionLoginSendingCredentialsMessageText':	"Invio delle credenziali",
'connectionLoginCredentialsVerificationMessageTitle':	"Verifica delle credenziali",
'connectionLoginCredentialsVerificationMessageText':	"Esecuzione dell&#x27;autenticazione SRP ...",
'connectionLoginDoneMessageTitle':	"Verifica delle credenziali",
'connectionLoginDoneMessageText':	"Connesso",
'userLoginPanelUpgradingUserCredentialsMessageTitle':	"Verifica delle credenziali",
'userLoginPanelUpgradingUserCredentialsMessageText':	"Aggiornamento delle credenziali ad un nuovo schema di autenticazione",
'userLoginPanelConnectedMessageTitle':	"Utente autenticato",
'userLoginPanelConnectedMessageText':	"Autenticazione eseguita con successo",
'userLoginPanelTryingAnOlderConnectionSchemaMessageTitle':	"Verifica delle credenziali",
'userLoginPanelTryingAnOlderConnectionSchemaMessageText':	"Tentativo con vecchio schema di autenticazione",
'userLoginPanelLoadingUserDataMessageTitle':	"Utente autenticato",
'userLoginPanelLoadingUserDataMessageText':	"Scarica le intestazioni criptate delle schede da Clipperz",
'userLoginPanelDecryptingUserDataMessageTitle':	"Utente autenticato",
'userLoginPanelDecryptingUserDataMessageText':	"Decodifica locale dell&#x27;intestazione delle schede",
'userLoginPanelDecryptingUserStatisticsMessageTitle':	"Utente autenticato",
'userLoginPanelDecryptingUserStatisticsMessageText':	"Decodifica locale delle statistiche d&#x27;uso",
'splashAlertTitle':	"Benvenuto a Clipperz!",
'splashAlertText':	"<p>Alcuni consigli per la sicurezza</p> <ul> <li> <p>La sicurezza dei tuoi dati dipende da quanto è sicura la frase segreta che usi per proteggerli. Nessuno può accedervi a meno che non conosca la frase segreta.</p> </li> <li> <p>Se hai intenzione di usare Clipperz per conservare informazioni sensibili e riservate, scegli attentamente una frase segreta complessa. Più è lunga, maggiore è la sicurezza!</p> </li> <li> <p>E non dimenticare che Clipperz non è in grado di recuperare la tua frase segreta in caso di smarrimento!</p> </li> </ul> <p>Per maggiori informazioni sulla sicurezza, consulta il sito <a href=\"http://www.clipperz.com\" target=\"_blank\">Clipperz</a> (in lingua inglese).</p> ",
'splashAlertCloseButtonLabel':	"Ok",
'registrationFormTitle':	"crea il tuo utente",
'registrationFormUsernameLabel':	"Utente",
'registrationFormPassphraseLabel':	"frase segreta",
'registrationFormRetypePassphraseLabel':	"ripeti frase segreta",
'registrationFormSafetyCheckLabel':	"Sono consapevole che Clipperz non è in grado di recuperare una frase segreta dimenticata.",
'registrationFormTermsOfServiceCheckLabel':	"Dichiaro di aver letto e di accettare i <a href=\"https://www.clipperz.com/terms_service\" target=\"_blank\">Termini del Servizio</a> .",
'registrationFormDoYouAlreadyHaveAnAccountLabel':	"sei già un utente registrato?",
'registrationFormSimplyLoginLabel':	"accedi subito",
'registrationFormButtonLabel':	"Registrati",
'registrationFormWarningMessageNotMatchingPassphrases':	"Le frasi segrete non corrispondono, ripeti l&#x27;inserimento.",
'registrationFormWarningMessageSafetyCheckNotSelected':	"Leggi e spunta le condizioni sotto riportate.",
'registrationFormWarningMessageTermsOfServiceCheckNotSelected':	"Per procedere devi accettare i Termini del Servizio.",
'registrationMessagePanelInitialTitle':	"Registrazione in corso ...",
'registrationMessagePanelInitialText':	"---",
'registrationMessagePanelInitialButtonLabel':	"Annulla",
'registrationMessagePanelRegistrationDoneTitle':	"Registrazione",
'registrationMessagePanelRegistrationDoneText':	"Fatto",
'registrationMessagePanelFailureTitle':	"Registrazione fallita",
'registrationMessagePanelFailureButtonLabel':	"Chiudi",
'connectionRegistrationSendingRequestMessageText':	"Verifica delle credenziali",
'connectionRegistrationSendingCredentialsMessageText':	"Invio delle credenziali",
'registrationSplashPanelTitle':	"Avviso di sicurezza",
'registrationSplashPanelDescription':	"<p>Queste sono le tue credenziali di accesso a Clipperz, conservale con cura. Il tuo utente ed la tua frase segreta non ti verranno mostrati una seconda volta!</p> ",
'registrationSplashPanelUsernameLabel':	"Utente",
'registrationSplashPanelPassphraseLabel':	"frase segreta",
'registrationSplashPanelShowPassphraseButtonLabel':	"mostra la frase segreta",
'donateHeaderLinkLabel':	"donazioni",
'creditsHeaderLinkLabel':	"credits",
'feedbackHeaderLinkLabel':	"scrivici",
'helpHeaderLinkLabel':	"aiuto",
'forumHeaderLinkLabel':	"forum",
'recordMenuLabel':	"Schede",
'accountMenuLabel':	"profilo",
'dataMenuLabel':	"dati",
'contactsMenuLabel':	"Contatti",
'toolsMenuLabel':	"strumenti",
'logoutMenuLabel':	"esci",
'lockMenuLabel':	"blocca",
'lockTitle':	"Utente bloccato",
'lockDescription':	"<p>Per sbloccare il tuo utente inserisci la frase segreta</p> ",
'unlockButtonLabel':	"Sblocca",
'changePasswordTabLabel':	"Cambia la tua frase segreta",
'changePasswordTabTitle':	"Cambia la tua frase segreta",
'changePasswordFormUsernameLabel':	"Utente",
'changePasswordFormOldPassphraseLabel':	"attuale frase segreta",
'changePasswordFormNewPassphraseLabel':	"nuova frase segreta",
'changePasswordFormRetypePassphraseLabel':	"ripeti nuova frase segreta",
'changePasswordFormSafetyCheckboxLabel':	"Sono consapevole che Clipperz non è in grado di recuperare una frase segreta dimenticata.",
'changePasswordFormSubmitLabel':	"Cambia frase segreta",
'changePasswordFormWrongUsernameWarning':	"Utente errato",
'changePasswordFormWrongPassphraseWarning':	"Frase segreta errata",
'changePasswordFormWrongRetypePassphraseWarning':	"Le frasi segrete non corrispondono, ripeti l&#x27;inserimento.",
'changePasswordFormSafetyCheckWarning':	"Leggi e spunta le condizioni sotto riportate.",
'changePasswordFormProgressDialogTitle':	"Aggiornamento credenziali",
'changePasswordFormProgressDialogEmptyText':	"---",
'changePasswordFormProgressDialogConnectedMessageTitle':	"Connesso",
'changePasswordFormProgressDialogConnectedMessageText':	"Fatto",
'changePasswordFormProgressDialogErrorMessageTitle':	"Errore",
'changePasswordFormProgressDialogErrorMessageText':	"Aggiornamento credenziali fallito!",
'changeCredentialsPanelEncryptingDataMessageTitle':	"Cambio della frase segreta",
'changeCredentialsPanelEncryptingDataMessageText':	"Cripta localmente l&#x27;intestazione delle schede",
'changeCredentialsPanelCreatingNewCredentialsMessageTitle':	"Cambio della frase segreta",
'changeCredentialsPanelCreatingNewCredentialsMessageText':	"Aggiornamento delle credenziali",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageTitle':	"Cambio della frase segreta",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageText':	"Carica le intestazioni criptate delle schede su Clipperz",
'changeCredentialsPanelDoneMessageTitle':	"Cambio della frase segreta",
'changeCredentialsPanelDoneMessageText':	"Fatto",
'manageOTPTabLabel':	"Codici di accesso “usa e getta”",
'manageOTPTabTitle':	"Codici di accesso “usa e getta”",
'manageOTPTabDescription':	"<p>I codici di accesso e “usa e getta” funzionano come la tua normale frase segreta, ma possono essere utilizzate una sola volta.</p> <p>Se lo stesso codice “usa e getta” viene utilizzato per tentare ulteriori accessi il processo di autenticazione fallirà.</p> <p>Infatti, dopo il primo utilizzo, il codice “usa e getta” verrà immediatamente disattivato e cancellato prevenendo così eventuali accessi non autorizzati.</p> <p>L&#x27;utilizzo di codici “usa e getta” è una scelta consigliata per chi teme che il computer dal quale sta accedendo a Clipperz non sia sicuro a causa di software quali keyloggers e spyware che potrebbero registrare le proprie credenziali di accesso.</p> <p><b>E&#x27; caldamente consigliato l&#x27;utilizzo di codici “usa e getta” quando ci si collega a Clipperz da terminali pubblici quali Internet Cafe e biblioteche.</b> </p> ",
'oneTimePasswordReadOnlyMessage':	"<h6>Attenzione!</h6> <p>Non è possibilie accedere ai propri codici “usa e getta” quando si utilizza la versione offline di Clipperz.</p> ",
'oneTimePasswordLoadingMessage':	"<h6>Caricamento dati</h6> <p>Si prega di attendere ...</p> ",
'oneTimePasswordNoPasswordAvailable':	"<h6>Nessun codice “usa e getta” disponibile</h6> <p>Per creare codici “usa e getta” clicca sul pulsante “Nuovo” che trovi qui sopra.</p> ",
'deleteOTPButtonLabel':	"Elimina",
'printOTPButtonLabel':	"Stampa",
'disabledOneTimePassword_warning':	"disabilitato",
'oneTimePasswordSelectionLink_selectLabel':	"Seleziona:",
'oneTimePasswordSelectionLink_none':	"nessuno",
'oneTimePasswordSelectionLink_used':	"utilizzati",
'oneTimePasswordSelectionLink_unused':	"disponibili",
'saveOTP_encryptUserDataTitle':	"Registrazione del nuovo codice “usa e getta”",
'saveOTP_encryptUserDataText':	"Elaborazione delle credenziali OTP ...",
'saveOTP_encryptOTPDataTitle':	"Registrazione del nuovo codice “usa e getta”",
'saveOTP_encryptOTPDataText':	"Codifica locale dei dati di autenticazione ...",
'saveOTP_sendingDataTitle':	"Registrazione del nuovo codice “usa e getta”",
'saveOTP_sendingDataText':	"Invio dei dati di autenticazione criptati ...",
'saveOTP_updatingInterfaceTitle':	"Registrazione del nuovo codice “usa e getta”",
'saveOTP_updatingInterfaceText':	"Aggiornamento dell&#x27;interfaccia",
'accountPreferencesLabel':	"Preferenze",
'accountPreferencesTabTitle':	"Preferenze",
'accountPreferencesLanguageTitle':	"Selezione della lingua",
'accountPreferencesLanguageDescription':	"<p>Scegli la lingua preferita dall&#x27;elenco sottostante.</p> ",
'showDonationReminderPanelTitle':	"Promemoria donazioni",
'showDonationReminderPanelDescription':	"<p>Mostra i promemopria per le donazioni</p> ",
'saveUserPreferencesFormSubmitLabel':	"Salva",
'cancelUserPreferencesFormSubmitLabel':	"Annulla",
'accountPreferencesSavingPanelTitle_Step1':	"Salvataggio preferenze",
'accountPreferencesSavingPanelText_Step1':	"Cripta localmente le preferenze",
'accountPreferencesSavingPanelTitle_Step2':	"Salvataggio preferenze",
'accountPreferencesSavingPanelText_Step2':	"Carica preferenze criptate su Clipperz",
'accountLoginHistoryLabel':	"Registro degli accessi",
'loginHistoryTabTitle':	"Registro degli accessi",
'loginHistoryReadOnlyMessage':	"<h6>Attenzione!</h6> <p>Il registro degli accessi non è disponibile quando si utilizza la versione offline di Clipperz</p> ",
'loginHistoryLoadingMessage':	"<h6>Caricamento dati</h6> <p>Si prega di attendere ...</p> ",
'loginHistoryLoadedMessage':	"<h6>I tuoi ultimi 10 accessi</h6> <p> </p> ",
'loginHistoryIPLabel':	"IP",
'loginHistoryTimeLabel':	"data",
'loginHistoryCurrentSessionText':	"sessione corrente",
'loginHistoryReloadButtonLabel':	"Aggiorna il registro degli accessi",
'deleteAccountTabLabel':	"Cancella il tuo utente",
'deleteAccountTabTitle':	"Cancella il tuo utente",
'deleteAccountFormUsernameLabel':	"Utente",
'deleteAccountFormPassphraseLabel':	"frase segreta",
'deleteAccountFormSafetyCheckboxLabel':	"Sono consapevole che tutti miei dati verranno cancellati e che questa azione è irreversibile.",
'deleteAccountFormSubmitLabel':	"Cancella il mio utente",
'deleteAccountFormWrongUsernameWarning':	"Utente errato",
'deleteAccountFormWrongPassphraseWarning':	"Frase segreta errata",
'deleteAccountFormSafetyCheckWarning':	"Leggi e spunta le condizioni sotto riportate.",
'accountPanelDeletingAccountPanelConfirmationTitle':	"ATTENZIONE",
'accountPanelDeleteAccountPanelConfirmationText':	"Sei sicuro di voler cancellare il tuo utente?",
'offlineCopyTabLabel':	"Copia offline",
'offlineCopyTabTitle':	"Copia offline",
'offlineCopyTabDescription':	"<p>Con un solo clic puoi trasferire tutti i tuoi dati dai server di Clipperz al tuo PC, creando una versione offline di Clipperz a cui potrai accedere quando non è disponibile un collegamento ad Internet.</p> <p>La versione offline in sola lettura è sicura quanto quella online e non espone i tuoi dati a livelli di rischio superiore in quanto entrambe condividono la medesima architettura di sicurezza.</p> <ol> <li> <p>Clicca sul link sottostante per scaricare la copia offline dei tuoi dati.</p> </li> <li> <p>Il browser ti chiederà cosa fare del file “Clipperz_YYYYMMDD.html”. Scegli di salvarlo su un disco locale.</p> </li> <li> <p>Basta un doppio click sul file appena scaricato per lanciare la versione offline di Clipperz.</p> </li> <li> <p>Accedi utilizzando le normali credenziali di accesso.</p> </li> </ol> ",
'offlineCopyDownloadLinkLabel':	"Scarica copia offline",
'offlineCopyDownloadWarning':	"<h4><a href=\"#\" id=\"offlineCopyDownloadWarningLink\">Aggiorna la tua “copia offline”!</a> </h4> <p>Una o più schede sono state recentemente create o modificate, ti consigliamo di scaricare nuovamente la tua “copia offline”.</p> ",
'offlineCopyDownloadOk':	"",
'sharingTabLabel':	"Condividi",
'sharingTabTitle':	"Condividi",
'sharingTabDescription':	"<p>Spesso è necessario condividere alcune delle proprie informazioni riservate con una o più persone.</p> <p>Può trattarsi di situazioni semplici come dare ad un collega il codice di accesso alla propria segreteria telefonica quando si va in vacanza, oppure complesse come regolare l&#x27;accesso dei legittimi eredi ai servizi di online banking utilizzati dal defunto.</p> <p>Con Clipperz la condivisione di segreti diviene un processo semplice e sicuro.</p> <p> </p> <p><b>Presto disponibile ...</b> </p> ",
'importTabLabel':	"Importa",
'importTabTitle':	"Importa",
'importTabDescription':	"<p>Presto disponibile ...</p> ",
'printingTabLabel':	"Esporta",
'printingTabTitle':	"Esporta",
'printingTabDescription':	"<h5>Stampa i tuoi dati</h5> <p>Cliccando sul link sottostante si aprirà una nuova finestra in cui verranno visualizzate tutte le tue schede in un formato idoneo alla stampa.</p> <p>Se intendi utilizzare la stampa per creare una copia di sicurezza dei tuoi dati, ti suggeriamo di considerare l&#x27;opzione più sicura fornita della “copia offline”.</p> ",
'printingLinkLabel':	"Versione stampabile",
'contactsTabLabel':	"Contatti",
'contactsTabTitle':	"Contatti",
'passwordGeneratorTabLabel':	"Generatore di password",
'bookmarkletTabLabel':	"Bookmarklet",
'passwordGeneratorTabTitle':	"Generatore di password",
'bookmarkletTabTitle':	"Bookmarklet",
'paswordGeneratorTabDescription':	"<p> </p> ",
'passwordGeneratorTabButtonLabel':	"Genera password",
'bookmarkletTabLabel':	"Bookmarklet",
'bookmarkletTabTitle':	"Bookmarklet",
'bookmarkletTabBookmarkletTitle':	"Aggiungi a Clipperz",
'bookmarkletTabInstructions':	"<h3>Come creare una scheda con “login diretto” ad un servizio online</h3> <ol> <li> <p>Aprire la pagina web che contiene la maschera di login. (ovvero la pagina dove usualmente si inseriscono nome utente e password)</p> </li> <li> <p>Cliccare sulla bookmarklet: una nuova finestrella si visualizzerà sopra la pagina.</p> </li> <li> <p>Copiare il testo di configurazione del “login diretto” contenuto nella finestrella. (ctrl-C)</p> </li> <li> <p>Accedere a Clipperz e cliccare sul pulsante <b>Aggiungi nuova scheda</b> .</p> </li> <li> <p>Selezionare il modello “Login diretto” ed incollare il testo precedentemente copiato. (ctrl-V)</p> </li> <li> <p>Cliccare sul pulsante <b>Crea</b> , completare e verificare i dettagli della scheda, quindi cliccare su <b>Salva</b> .</p> </li> </ol> <h3>Come aggiungere un “login diretto” ad una scheda esistente</h3> <ol> <li> <p>Come sopra.</p> </li> <li> <p>Come sopra.</p> </li> <li> <p>Come sopra.</p> </li> <li> <p>Accedere a Clipperz e selezionare la scheda contenente le credenziali del servizio a cui si vuole accedere con il “login diretto” e cliccare su <b>Modifica</b> .</p> </li> <li> <p>Incollare il testo precedentemente copiato nell&#x27;apposito campo presente nella sezione “Login diretti”. (ctrl-V)</p> </li> <li> <p>Cliccare il pulsante <b>Aggiungi nuovo login diretto</b> , completare e verificare i dettagli della scheda, quindi cliccare su <b>Salva</b> .</p> </li> </ol> <p> </p> <p>Ulteriori informazioni sull&#x27;utilizzo della bookmarklet sono <a href=\"http://www.clipperz.com/support/user_guide/bookmarklet\" target=\"_blank\">disponibili qui</a> .</p> ",
'mainPanelDirectLoginBlockLabel':	"Login diretti",
'directLinkReferenceShowButtonLabel':	"mostra",
'mainPanelDirectLoginBlockDescription':	"<p>Crea “login diretti” per accedere ai tuoi servizi web senza bisogno di inserire username e password!</p> <p>I “login diretti” migliorano la tua sicurezza permettendoti di:</p> <ul> <li> <p>adottare comodamente password complesse;</p> </li> <li> <p>non riutilizzare mai la stessa password.</p> </li> </ul> <p>Semplice e rapido grazie alla <b>Clipperz bookmarklet</b> .</p><a href=\"http://www.clipperz.com/support/user_guide/direct_logins\" target=\"_blank\">Ulteriori informazioni</a> ",
'mainPanelRecordsBlockLabel':	"Schede",
'mainPanelAddRecordButtonLabel':	"Aggiungi nuova scheda",
'mainPanelRemoveRecordButtonLabel':	"Elimina scheda",
'mainPanelRecordFilterBlockTagsLabel':	"tags",
'recordDetailNoRecordAtAllTitle':	"Benvenuto a Clipperz!",
'recordDetailNoRecordAtAllDescription':	"<h5>Ora puoi iniziare ad aggiungere schede con le tue informazioni riservate.</h5> <p>Le schede sono semplici moduli in cui organizzare le tue password ed ogni altro tipo di dato confidenziale.</p> <p>Le schede hanno una struttura flessibile e si adattano a contenere le informazioni più diverse: dalle password ai dettagli delle tue carte di credito!</p> <h5>Non dimenticarti di installare la bookmarklet!</h5> <p>Prima di iniziare ti consigliamo di installare la bookmarklet “Aggiungi a Clipperz”: creare nuove schede diventerà più rapido e divertente.</p> <p>Vai alla sezione “bookmarklet” per scoprire come installarla ed utilizzarla.</p> <p> </p> <p>Quando sei pronto, clicca sul pulsante <b>Aggiungi nuova scheda</b> e metti al sicuro tutte le tue informazioni più preziose.</p> <p> </p><a href=\"http://www.clipperz.com/support/user_guide/managing_cards\" target=\"_blank\">Maggiori informazioni sulla creazione e gestione delle schede (in inglese)</a> ",
'newRecordWizardTitleBox':	"<h5>Seleziona un modello di scheda</h5> <p>Le schede sono semplici moduli in cui organizzare le tue password ed ogni altro tipo di dato confidenziale.</p> <p>Scegli un modello dall&#x27;elenco sottostante. In seguito potrai sempre modificare la tua scheda aggiungendo o rimuovendo campi.</p> ",
'newRecordWizardBookmarkletConfigurationTitle':	"Login diretto",
'newRecordWizardBookmarkletConfigurationDescription':	"<p>Incolla qui sotto il codice generato dalla bookmarklet di Clipperz.</p> <p>Verrà creata una nuova scheda già completa con le informazioni per il “login diretto” al tuo servizio web.</p> ",
'newRecordWizardCreateButtonLabel':	"Crea",
'newRecordWizardCancelButtonLabel':	"Annulla",
'donateSplashPanelTitle':	"Supporta Clipperz, fai una donazione oggi!",
'donateSplashPanelDescription':	"<p>Alcune buone ragioni per fare una donazione:</p> <ul> <li> <p>supportare lo sviluppo di nuove funzionalità</p> </li> <li> <p>mantenere il servizio gratuito per tutti</p> </li> <li> <p>mostrare la tua gratitudine per il nostro duro lavoro</p> </li> </ul> <p>Per qualunque ulteriore informazione visita la <a href=\"http://www.clipperz.com/donations\" target=\"_blank\">pagina delle donazioni</a> .</p> <p><b>Pronto a donare?</b> </p> ",
'donateCloseButtonLabel':	"Non ancora",
'recordTemplates':	{
	'WebAccount':	{
		'title':	"Password",
		'description':	"<p>Una scheda molto semplice per conservare le credenziali di accesso ai tuoi servizi web.</p> ",
		'fields':	{
			'URL':	"Indirizzo web",
			'TXT':	"Utente o email",
			'PWD':	"Password"
		}
	},
	'BankAccount':	{
		'title':	"Conto corrente bancario",
		'description':	"<p>Proteggi il tuo numero di conto corrente ed i codici di accesso ai servizi di online banking.</p> ",
		'fields':	{
			'TXT':	"Banca",
			'TXT':	"Conto corrente n.",
			'URL':	"Sito web della banca",
			'TXT':	"Online banking ID",
			'PWD':	"Online banking password"
		}
	},
	'CreditCard':	{
		'title':	"Carta di credito",
		'description':	"<p>Numero della carta, data di scadenza, codici CVV2 e PIN sempre a portata di mano con Clipperz.</p> ",
		'fields':	{
			'TXT':	"Tipo (Visa, AmEx, ...)",
			'TXT':	"Numero",
			'TXT':	"Titolare",
			'TXT':	"Data di scadenza",
			'TXT':	"CVV2",
			'PWD':	"PIN",
			'URL':	"Sito web della carta",
			'TXT':	"Utente",
			'PWD':	"Password"
		}
	},
	'AddressBookEntry':	{
		'title':	"Voce della rubrica",
		'description':	"<p>Fai di Clipperz la tua rubrica segreta. Usa questo modello per creare una nuova voce.</p> ",
		'fields':	{
			'TXT':	"Nome",
			'TXT':	"Email",
			'TXT':	"Telefono",
			'TXT':	"Cellulare",
			'ADDR':	"Indirizzo"
		}
	},
	'Custom':	{
		'title':	"Scheda personalizzata",
		'description':	"<p>Qualunque sia il tipo di informazione che desideri proteggere, Clipperz ti consente di creare una scheda su misura per i tuoi bisogni.</p> ",
		'fields':	{
			'TXT':	"Nome del campo 1",
			'TXT':	"Nome del campo 2",
			'TXT':	"Nome del campo 3"
		}
	}
},
'recordFieldTypologies':	{
	'TXT':	{
		'description':	"simple text field"
	},
	'PWD':	{
		'description':	"simple text field, with default status set to hidden",
		'shortDescription':	"Password"
	},
	'URL':	{
		'description':	"simple text field in edit mode, that became an active url in view mode",
		'shortDescription':	"Indirizzo web"
	},
	'DATE':	{
		'description':	"a value set with a calendar helper",
		'shortDescription':	"data"
	},
	'ADDR':	{
		'description':	"just like the URL, but the active link points to Google Maps (or similar service) passing the address value as argument",
		'shortDescription':	"indirizzo stradale"
	},
	'CHECK':	{
		'description':	"check description",
		'shortDescription':	"check"
	},
	'RADIO':	{
		'description':	"radio description",
		'shortDescription':	"radio"
	},
	'SELECT':	{
		'description':	"select description",
		'shortDescription':	"Seleziona:"
	}
},
'newRecordPanelGeneralExceptionTitle':	"Errore",
'newRecordPanelGeneralExceptionMessage':	"Configurazione non valida. Accertati di aver utilizzato il codice quello generato dalla bookmarklet.",
'newRecordPanelWrongBookmarkletVersionExceptionTitle':	"Errore",
'newRecordPanelWrongBookmarkletVersionExceptionMessage':	"La configurazione è stato generata da una vecchia versione della bookmarklet. Sei pregato di aggiornare subito la tua bookmarklet.",
'newRecordPanelExceptionPanelCloseButtonLabel':	"Annulla",
'mainPanelDeletingRecordPanelConfirmationTitle':	"Eliminazione della scheda in corso",
'mainPanelDeleteRecordPanelConfirmationText':	"Vuoi veramente eliminare la scheda selezionata?",
'mainPanelDeletingRecordPanelInitialTitle':	"Eliminazione della scheda in corso",
'mainPanelDeletingRecordPanelInitialText':	"---",
'mainPanelDeletingRecordPanelCompletedText':	"Fatto",
'deleteRecordPanelCollectRecordDataMessageTitle':	"Elimina scheda",
'deleteRecordPanelCollectRecordDataMessageText':	"Aggiorna elenco delle schede",
'deleteRecordPanelEncryptUserDataMessageTitle':	"Elimina scheda",
'deleteRecordPanelEncryptUserDataMessageText':	"Cripta localmente l&#x27;intestazione delle schede",
'deleteRecordPanelSendingDataToTheServerMessageTitle':	"Elimina scheda",
'deleteRecordPanelSendingDataToTheServerMessageText':	"Carica le intestazioni criptate delle schede su Clipperz",
'deleteRecordPanelUpdatingTheInterfaceMessageTitle':	"Elimina scheda",
'deleteRecordPanelUpdatingTheInterfaceMessageText':	"Aggiornamento dell&#x27;interfaccia",
'recordDetailNoRecordSelectedTitle':	"Nessuna scheda selezionata",
'recordDetailNoRecordSelectedDescription':	"<p>Selezionare una scheda dall&#x27;elenco a sinistra.</p> ",
'recordDetailLoadingRecordMessage':	"Scarica scheda criptata da Clipperz",
'recordDetailDecryptingRecordMessage':	"Decodifica locale dei dati della scheda",
'recordDetailLoadingRecordVersionMessage':	"Scarica l&#x27;ultima versione della scheda",
'recordDetailDecryptingRecordVersionMessage':	"Decodifica locale dell&#x27;ultima versione",
'recordDetailLoadingErrorMessageTitle':	"Errore nello scaricamento della scheda",
'recordDetailNotesLabel':	"Note",
'recordDetailLabelFieldColumnLabel':	"Nome del campo",
'recordDetailDataFieldColumnLabel':	"Dati del campo",
'recordDetailTypeFieldColumnLabel':	"Tipo",
'recordDetailSavingChangesMessagePanelInitialTitle':	"Salvataggio scheda",
'recordDetailSavingChangesMessagePanelInitialText':	"---",
'recordDetailRemoveFieldButtonLabel':	"-",
'recordDetailAddFieldButtonLabel':	"Aggiungi nuovo campo",
'recordDetailPasswordFieldHelpLabel':	"clicca le stelline per copiare la password e poi Ctrl-C",
'recordDetailPasswordFieldScrambleLabel':	"nascondi",
'recordDetailPasswordFieldUnscrambleLabel':	"mostra",
'recordDetailDirectLoginBlockTitle':	"Login diretti",
'recordDetailNewDirectLoginDescription':	"<p>Configurazione del login diretto</p> ",
'recordDetailDirectLoginBlockNoDirectLoginConfiguredDescription':	"<p>Questa scheda contiene credenziali di accesso ad un servizio online?</p> <p>In tal caso puoi utilizzare la bookmarklet per configurare un “login diretto” da Clipperz con un solo clic!</p> ",
'recordDetailDeleteDirectLoginButtonLabel':	"-",
'recordDetailAddNewDirectLoginButtonLabel':	"Aggiungi nuovo login diretto",
'recordDetailEditButtonLabel':	"Modifica",
'recordDetailSaveButtonLabel':	"Salva",
'recordDetailCancelButtonLabel':	"Annulla",
'newRecordTitleLabel':	"_nuova scheda_",
'newDirectLoginLabelSuffix':	"",
'recordSaveChangesPanelCollectRecordInfoMessageTitle':	"Salva scheda",
'recordSaveChangesPanelCollectRecordInfoMessageText':	"Aggiorna elenco delle schede",
'recordSaveChangesPanelEncryptUserDataMessageTitle':	"Salva scheda",
'recordSaveChangesPanelEncryptUserDataMessageText':	"Cripta localmente l&#x27;intestazione delle schede",
'recordSaveChangesPanelEncryptRecordDataMessageTitle':	"Salva scheda",
'recordSaveChangesPanelEncryptRecordDataMessageText':	"Cripta localmente i dati della scheda",
'recordSaveChangesPanelEncryptRecordVersionDataMessageTitle':	"Salva scheda",
'recordSaveChangesPanelEncryptRecordVersionDataMessageText':	"Cripta localmente la versione della scheda",
'recordSaveChangesPanelSendingDataToTheServerMessageTitle':	"Salva scheda",
'recordSaveChangesPanelSendingDataToTheServerMessageText':	"Carica le intestazioni criptate delle schede su Clipperz",
'recordSaveChangesPanelUpdatingTheInterfaceMessageTitle':	"Salva scheda",
'recordSaveChangesPanelUpdatingTheInterfaceMessageText':	"Aggiornamento dell&#x27;interfaccia",
'passwordGeneratorPanelTitle':	"Generatore di password",
'passwordGeneratorPanelOkLabel':	"Ok",
'passwordGeneratorPanelCancelLabel':	"Annulla",
'passwordGeneratorLengthLabel':	"lung . :",
//'DWRUtilLoadingMessage':	"Caricamento dati",
'comingSoon':	"Presto disponibile ...",
'panelCollectingEntryopyMessageText':	"Raccolta entropia",
'importData_parsingDataTitle':	"Importa",
'importData_previewingDataTitle':	"Importa",
'importData_processingDataTitle':	"Importa",
'ImportWizard':	{
	'EDIT':	"Modifica",
	'IMPORT':	"Importa",
	'CSV_NOTES':	"Note",
	'EXCEL_EDIT':	"Modifica"
},
'importData_importConfirmation_title':	"Importa",
'WELCOME_BACK':	"Bentornato!",
'currentConnectionText':	"Sei collegato da ip __ip__; probabilmente in __country__, utilizzando __browser__ con __operatingSystem__.",
'latestConnectionText':	"Il tuo ultimo accesso è stato __elapsedTimeDescription__ (__time__) da ip __ip__; probabilmente in __country__, utilizzando __browser__ con __operatingSystem__.",
'fullLoginHistoryLinkLabel':	"vai al registro degli accessi",
'elapsedTimeDescriptions':	{
	'MORE_THAN_A_MONTH_AGO':	"più di un mese fa",
	'MORE_THAN_A_WEEK_AGO':	"più di una settimana fa",
	'MORE_THAN_*_WEEKS_AGO':	"più di __elapsed__ settimane fa",
	'YESTERDAY':	"ieri",
	'*_DAYS_AGO':	"__elapsed__ giorni fa",
	'ABOUT_AN_HOUR_AGO':	"circa un&#x27;ora fa",
	'*_HOURS_AGO':	"__elapsed__ ore fa",
	'JUST_A_FEW_MINUTES_AGO':	"pochi minuti fa",
	'ABOUT_*_MINUTES_AGO':	"circa __elapsed__ minuti fa"
},
'unknown_ip':	"sconosciuto",
'countries':	{
	'--':	"sconosciuto",
	'AD':	"Andorra",
	'AE':	"Emirati arabi uniti",
	'AF':	"Afghanistan",
	'AG':	"Antigua e Barbuda",
	'AI':	"Anguilla",
	'AL':	"Albania",
	'AM':	"Armenia",
	'AN':	"Antille olandesi",
	'AO':	"Angola",
	'AR':	"Argentina",
	'AS':	"Samoa americane",
	'AT':	"Austria",
	'AU':	"Australia",
	'AW':	"Aruba",
	'AZ':	"Azerbaigian",
	'BB':	"Barbados",
	'BD':	"Bangladesh",
	'BE':	"Belgio",
	'BF':	"Burkina-Faso",
	'BG':	"Bulgaria",
	'BH':	"Bahrein",
	'BI':	"Burundi",
	'BJ':	"Benin",
	'BM':	"Bermuda",
	'BN':	"Brunei",
	'BO':	"Bolivia",
	'BR':	"Brasile",
	'BS':	"Bahamas",
	'BT':	"Bhutan",
	'BW':	"Botswana",
	'BY':	"Bielorussia",
	'BZ':	"Belize",
	'CA':	"Canada",
	'CD':	"Repubblica democratica del Congo",
	'CF':	"Repubblica centrafricana",
	'CH':	"Svizzera",
	'CK':	"Isole Cook",
	'CL':	"Cile",
	'CM':	"Camerun",
	'CN':	"Cina",
	'CO':	"Colombia",
	'CR':	"Costa Rica",
	'CS':	"Repubblica del Montenegro",
	'CU':	"Cuba",
	'CY':	"Cipro",
	'CZ':	"Repubblica ceca",
	'DE':	"Germania",
	'DJ':	"Gibuti",
	'DK':	"Danimarca",
	'DO':	"Repubblica dominicana",
	'DZ':	"Algeria",
	'EC':	"Ecuador",
	'EE':	"Estonia",
	'EG':	"Egitto",
	'ER':	"Eritrea",
	'ES':	"Spagna",
	'ET':	"Etiopia",
	'FI':	"Finlandia",
	'FJ':	"Figi",
	'FM':	"Micronesia",
	'FO':	"Isole Fær Øer",
	'FR':	"Francia",
	'GA':	"Gabon",
	'GB':	"Regno Unito",
	'GD':	"Grenada",
	'GE':	"Georgia",
	'GF':	"Guyana francese",
	'GG':	"Guernsey",
	'GH':	"Ghana",
	'GI':	"Gibilterra",
	'GL':	"Groenlandia",
	'GM':	"Gambia",
	'GP':	"Guadalupa",
	'GR':	"Grecia",
	'GT':	"Guatemala",
	'GU':	"Guam",
	'GW':	"Guinea-Bissau",
	'GY':	"Guyana",
	'HK':	"Hong Kong",
	'HN':	"Honduras",
	'HT':	"Haiti",
	'HU':	"Ungheria",
	'ID':	"Indonesia",
	'IE':	"Irlanda",
	'IL':	"Israele",
	'IM':	"Isola di Man",
	'IN':	"India",
	'IO':	"Territorio britannico dell&#x27;Oceano Indiano",
	'IQ':	"Iraq",
	'IR':	"Iran",
	'IS':	"Islanda",
	'IT':	"Italia",
	'JE':	"Jersey",
	'JM':	"Giamaica",
	'JO':	"Giordania",
	'JP':	"Giappone",
	'KE':	"Kenya",
	'KG':	"Kirghizistan",
	'KH':	"Cambogia",
	'KI':	"Kiribati",
	'KN':	"Saint Kitts e Nevis",
	'KR':	"Corea del Sud",
	'KW':	"Kuwait",
	'KY':	"Isole Cayman",
	'KZ':	"Kazakistan",
	'LA':	"Laos",
	'LB':	"Libano",
	'LC':	"Saint Lucia",
	'LI':	"Liechtenstein",
	'LK':	"Sri Lanka",
	'LR':	"Liberia",
	'LS':	"Lesotho",
	'LT':	"Lituania",
	'LU':	"Lussemburgo",
	'LV':	"Lettonia",
	'LY':	"Libia",
	'MA':	"Marocco",
	'MC':	"Monaco",
	'MD':	"Moldova",
	'MG':	"Madagascar",
	'MH':	"Isole Marshall",
	'ML':	"Mali",
	'MM':	"Myanmar",
	'MN':	"Mongolia",
	'MP':	"Marianne settentrionali",
	'MR':	"Mauritania",
	'MS':	"Montserrat",
	'MT':	"Malta",
	'MU':	"Maurizio",
	'MV':	"Maldive",
	'MW':	"Malawi",
	'MX':	"Messico",
	'MY':	"Malaysia",
	'MZ':	"Mozambico",
	'NA':	"Namibia",
	'NC':	"Nuova Caledonia",
	'NF':	"Isola Norfolk",
	'NG':	"Nigeria",
	'NI':	"Nicaragua",
	'NL':	"Paesi Bassi",
	'NO':	"Norvegia",
	'NP':	"Nepal",
	'NR':	"Nauru",
	'NU':	"Niue",
	'NZ':	"Nuova Zelanda",
	'OM':	"Oman",
	'PA':	"Panama",
	'PE':	"Perù",
	'PF':	"Polinesia francese",
	'PG':	"Papua Nuova Guinea",
	'PH':	"Filippine",
	'PK':	"Pakistan",
	'PL':	"Polonia",
	'PR':	"Puerto Rico",
	'PS':	"Territori palestinesi",
	'PT':	"Portogallo",
	'PW':	"Palau",
	'PY':	"Paraguay",
	'QA':	"Qatar",
	'RO':	"Romania",
	'RS':	"Serbia",
	'RU':	"Russia",
	'RW':	"Ruanda",
	'SA':	"Arabia Saudita",
	'SB':	"Isole Salomone",
	'SC':	"Seicelle",
	'SD':	"Sudan",
	'SE':	"Svezia",
	'SG':	"Singapore",
	'SI':	"Slovenia",
	'SL':	"Sierra Leone",
	'SM':	"San Marino",
	'SN':	"Senegal",
	'SR':	"Suriname",
	'SV':	"El Salvador",
	'SY':	"Siria",
	'SZ':	"Swaziland",
	'TC':	"Turks e Caicos",
	'TG':	"Togo",
	'TH':	"Thailandia",
	'TJ':	"Tagikistan",
	'TM':	"Turkmenistan",
	'TN':	"Tunisia",
	'TO':	"Tonga",
	'TR':	"Turchia",
	'TV':	"Tuvalu",
	'TW':	"Taiwan",
	'TZ':	"Tanzania",
	'UA':	"Ucraina",
	'UG':	"Uganda",
	'US':	"Stati Uniti",
	'UY':	"Uruguay",
	'UZ':	"Uzbekistan",
	'VA':	"Santa Sede (Stato della Città del Vaticano)",
	'VE':	"Venezuela",
	'VG':	"Isole Vergini britanniche",
	'VI':	"Isole Vergini statunitensi",
	'VN':	"Vietnam",
	'VU':	"Vanuatu",
	'WS':	"Samoa",
	'YE':	"Yemen",
	'ZA':	"Sud Africa",
	'ZM':	"Zambia",
	'ZW':	"Zimbabwe"
},
'browsers':	{
	'UNKNOWN':	"sconosciuto"
},
'operatingSystems':	{
	'UNKNOWN':	"sconosciuto",
	'MOBILE':	"Cellulare"
},
'calendarStrings':	{
	'months':	{
		'0':	"Gennaio",
		'1':	"Febbraio",
		'2':	"Marzo",
		'3':	"Aprile",
		'4':	"Mag",
		'5':	"Giugno",
		'6':	"Luglio",
		'7':	"Agosto",
		'8':	"Settembre",
		'9':	"Ottobre",
		'10':	"Novembre",
		'11':	"Dicembre"
	},
	'shortMonths':	{
		'0':	"Gen",
		'1':	"Feb",
		'2':	"Mar",
		'3':	"Apr",
		'4':	"Mag",
		'5':	"Giu",
		'6':	"Lug",
		'7':	"Ago",
		'8':	"Set",
		'9':	"Ott",
		'10':	"Nov",
		'11':	"Dic"
	},
	'days':	{
		'0':	"Domenica",
		'1':	"Lunedì",
		'2':	"Martedì",
		'3':	"Mercoledì",
		'4':	"Giovedì",
		'5':	"Venerdì",
		'6':	"Sabato"
	},
	'shortDays':	{
		'0':	"Dom",
		'2':	"Mar",
		'3':	"Mer",
		'4':	"Gio",
		'5':	"Ven",
		'6':	"Sab"
	},
	'veryShortDays':	{
		'1':	"Lu",
		'4':	"Gi",
		'5':	"Ve"
	}
},

__syntaxFix__: "syntax fix"
});
