/*

Copyright 2008-2011 Clipperz Srl

This file is part of Clipperz's Javascript Crypto Library.
Javascript Crypto Library provides web developers with an extensive
and efficient set of cryptographic functions. The library aims to
obtain maximum execution speed while preserving modularity and
reusability.
For further information about its features and functionalities please
refer to http://www.clipperz.com

* Javascript Crypto Library is free software: you can redistribute
  it and/or modify it under the terms of the GNU Affero General Public
  License as published by the Free Software Foundation, either version
  3 of the License, or (at your option) any later version.

* Javascript Crypto Library is distributed in the hope that it will
  be useful, but WITHOUT ANY WARRANTY; without even the implied
  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Affero General Public License for more details.

* You should have received a copy of the GNU Affero General Public
  License along with Javascript Crypto Library.  If not, see
  <http://www.gnu.org/licenses/>.

*/

Clipperz.PM.Strings.Languages['ru-RU'.toLowerCase()] = MochiKit.Base.merge(Clipperz.PM.Strings.Languages['en-us'], {
'clipperzServiceDescription':	"<h2>Держи при себе!</h2> <ul> <li> <h3>Clipperz - это:</h3> <ul> <li> <p>безопасный и простой менеджер паролей</p> </li> <li> <p>эффективное решение для единой регистрации</p> </li> <li> <p>цифровое хранилище Ваших конфидециальных данных</p> </li> </ul> </li> <li>
			<h3>C помошью Clipperz Вы можете:</h3> <ul>
				<li> <p>хранить и управлять Вашими паролями</p> </li> <li> <p>входить в любые веб-сервисы без ввода логина и пароля</p> </li> <li> <p>защитить все  важные данные: коды охранной сигнализации, ПИНы, номера кредитных кард, ...</p> </li> <li> <p>открыть доступ Вашим членам семьи, друзьям, коллегам</p> </li> </ul> </li> <li>
			<h3>Преимущества Clipperz:</h3> <ul>
				<li> <p>бесплатный и абсолютно анонимный</p> </li> <li> <p>доступен в любое время и с любого компьютера</p> </li> <li> <p>не нужно ничего устанавливать</p> </li> <li> <p>не надо хранить секреты на компьютере или бумаге</p> </li> </ul> </li> <li>
			<h3>Безопасность Clipperz:</h3> <ul>
				<li> <p>все данные перед отправкой в Clipperz шифруются в браузере</p> </li> <li> <p>секретный ключ - это фраза, которую знаете только Вы</p> </li> <li> <p>Clipperz управляет важными данными в зашифрованном виде и никогда не получит доступ к ним в открытом виде</p> </li> <li> <p>Clipperz основан на стандартных криптографических протоколах: без каких-либо самоделок</p> </li> <li> <p>Вы можете просмотреть исходный код, но Вам ничего не надо знать о криптографии, чтобы быть просто пользоваться</p> </li> </ul> </li> <li>
			<a href=\"http://www.clipperz.com\" target=\"_blank\">Подробнее</a> </li> </ul> ",
'loginFormTitle':	"войти под Вашим аккаунтом Clipperz",
'loginFormUsernameLabel':	"имя пользователя",
'loginFormPassphraseLabel':	"ключевая фраза",
'loginFormDontHaveAnAccountLabel':	"у вас еще нет аккаунта?",
'loginFormCreateOneLabel':	"создать",
'loginFormForgotYourCredentialsLabel':	"забыли пароль?",
'loginFormAarghThatsBadLabel':	"о! это плохо!",
'loginFormAfraidOfMaliciousScriptsLabel':	"опасаетесь вредоносных скриптов?",
'loginFormVerifyTheCodeLabel':	"проверить код",
'loginFormButtonLabel':	"Войти",
'loginFormOneTimePasswordCheckboxLabel':	"использовать одноразовую ключевую фразу",
'loginPanelSwithLanguageDescription':	"<h5>Переключиться на Ваш язык</h5> ",
'browserCompatibilityDescription':	"<p>Лучше работать с Clipperz в Firefox. Однако Clipperz хорошо совместим с Opera и MS Internet Explorer!</p> ",
'OTPloginMessagePanelInitialTitle':	"Вход",
'OTPloginMessagePanelInitialText':	"Передача данных учетной записи ...",
'OTPloginMessagePanelLoadingTitle':	"Вход",
'OTPloginMessagePanelLoadingText':	"Запрос аутентификационных данных с сервера ...",
'OTPloginMessagePanelProcessingTitle':	"Вход",
'OTPloginMessagePanelProcessingText':	"Расшифровка аутентификационных данных",
'loginMessagePanelInitialTitle':	"Вход ...",
'loginMessagePanelInitialButtonLabel':	"Отмена",
'loginMessagePanelConnectedTitle':	"Соединен",
'loginMessagePanelConnectedText':	"Выполнен",
'loginMessagePanelFailureTitle':	"Ошибка",
'loginMessagePanelFailureText':	"Ошибка при попытке входа",
'loginMessagePanelFailureButtonLabel':	"Закрыть",
'connectionLoginSendingCredentialsMessageTitle':	"Проверка учетной записи",
'connectionLoginSendingCredentialsMessageText':	"Передача данных ...",
'connectionLoginCredentialsVerificationMessageTitle':	"Проверка учетной записи",
'connectionLoginCredentialsVerificationMessageText':	"Выполняем SRP-аутентификацию ...",
'connectionLoginDoneMessageTitle':	"Проверка учетной записи",
'connectionLoginDoneMessageText':	"Соединено",
'userLoginPanelUpgradingUserCredentialsMessageTitle':	"Проверка учетной записи",
'userLoginPanelUpgradingUserCredentialsMessageText':	"Обновляем полномочия к новой схеме аутентификации",
'userLoginPanelConnectedMessageTitle':	"Пользователь аутентифицирован",
'userLoginPanelConnectedMessageText':	"Успешный вход",
'userLoginPanelTryingAnOlderConnectionSchemaMessageTitle':	"Проверка учетной записи",
'userLoginPanelTryingAnOlderConnectionSchemaMessageText':	"Пробуем войти по старой схеме",
'userLoginPanelLoadingUserDataMessageTitle':	"Пользователь аутентифицирован",
'userLoginPanelLoadingUserDataMessageText':	"Загрузка зашифрованных заголовков карточек",
'userLoginPanelDecryptingUserDataMessageTitle':	"Пользователь аутентифицирован",
'userLoginPanelDecryptingUserDataMessageText':	"Расшифровка заголовков карточек",
'userLoginPanelDecryptingUserStatisticsMessageTitle':	"Пользователь аутентифицирован",
'userLoginPanelDecryptingUserStatisticsMessageText':	"Расшифровка статистики",
'splashAlertTitle':	"Добро пожаловать в Clipperz!",
'splashAlertText':	"<p>Несколько советов по безопасности:</p> <ul> <li> <p>Хранение данных в Clipperz зависит от того, насколько безопасна выбранная Вами ключевая фраза</p> </li> <li> <p>Если собираетесь использовать Clipperz для защиты важных или критических данных, то убедитесь, что выбрали сложный пароль</p> </li> <li> <p>Clipperz не может восстановить забытую ключевую фразу</p> </li> </ul> <p>За дополнительной информацией обратитесь на <a href=\"http://www.clipperz.com\" target=\"_blank\">сайт</a> Clipperz.</p> ",
'splashAlertCloseButtonLabel':	"OK",
'registrationFormTitle':	"создать аккаунт",
'registrationFormUsernameLabel':	"имя пользователя",
'registrationFormPassphraseLabel':	"ключевая фраза",
'registrationFormRetypePassphraseLabel':	"повторите ключевую фразу",
'registrationFormSafetyCheckLabel':	"Я понимаю, что Clipperz не может восстановить забытую ключевую фразу",
'registrationFormTermsOfServiceCheckLabel':	"Я прочитал и согласен с <a href='http://www.clipperz.com/terms_of_service' target='_blank'>Условиями предоставления услуг</a>.",
'registrationFormDoYouAlreadyHaveAnAccountLabel':	"у вас уже есть аккаунт?",
'registrationFormSimplyLoginLabel':	"просто ввойдите",
'registrationFormButtonLabel':	"Зарегистрировать",
'registrationFormWarningMessageNotMatchingPassphrases':	"Ключевые фразы не совпадают, пожайлуста, повторите ввод",
'registrationFormWarningMessageSafetyCheckNotSelected':	"Прочитайте и проверьте все поля ниже",
'registrationFormWarningMessageTermsOfServiceCheckNotSelected':	"Вы должны принять Условия предоставления услуг",
'registrationMessagePanelInitialTitle':	"Создание аккаунта",
'registrationMessagePanelInitialButtonLabel':	"Отмена",
'registrationMessagePanelRegistrationDoneTitle':	"Регистрация",
'registrationMessagePanelRegistrationDoneText':	"Выполнено",
'registrationMessagePanelFailureTitle':	"Ошибка регистрации",
'registrationMessagePanelFailureButtonLabel':	"Закрыть",
'connectionRegistrationSendingRequestMessageText':	"Проверка учетной записи",
'connectionRegistrationSendingCredentialsMessageText':	"Передача данных",
'registrationSplashPanelTitle':	"Совет",
'registrationSplashPanelDescription':	"<p>Это Ваши данные учетной записи, позаботесь об их безопасности. Clipperz никогда больше не покажет Ваше имя пользователя и ключевую фразу!</p> ",
'registrationSplashPanelUsernameLabel':	"имя пользователя",
'registrationSplashPanelPassphraseLabel':	"ключевая фраза",
'registrationSplashPanelShowPassphraseButtonLabel':	"показать ключевую фразу",
'donateHeaderLinkLabel':	"пожертвования",
'creditsHeaderLinkLabel':	"список разработчиков",
'feedbackHeaderLinkLabel':	"обратная связь",
'helpHeaderLinkLabel':	"помощь",
'forumHeaderLinkLabel':	"форум",
'recordMenuLabel':	"карточки",
'accountMenuLabel':	"аккаунт",
'dataMenuLabel':	"данные",
'contactsMenuLabel':	"контакты",
'toolsMenuLabel':	"инструменты",
'logoutMenuLabel':	"выйти",
'lockMenuLabel':	"заблокировать",
'lockTitle':	"Аккаунт заблокирован",
'lockDescription':	"<p>Введите ключевую фразу для разблокировки</p> ",
'unlockButtonLabel':	"разблокировать",
'changePasswordTabLabel':	"Изменить ключевую фразу",
'changePasswordTabTitle':	"Изменить ключевую фразу",
'changePasswordFormUsernameLabel':	"имя пользователя",
'changePasswordFormOldPassphraseLabel':	"старая ключевая фраза",
'changePasswordFormNewPassphraseLabel':	"новая ключевая фраза",
'changePasswordFormRetypePassphraseLabel':	"повторить ключевую фразу",
'changePasswordFormSafetyCheckboxLabel':	"Я понимаю, что Clipperz не может восстановить забытую ключевую фразу.",
'changePasswordFormSubmitLabel':	"Изменить",
'changePasswordFormWrongUsernameWarning':	"Неправильное имя пользователя",
'changePasswordFormWrongPassphraseWarning':	"Неверная ключевая фраза",
'changePasswordFormWrongRetypePassphraseWarning':	"Ключевые фразы не совпадают, пожайлуста, повторите ввод.",
'changePasswordFormSafetyCheckWarning':	"Прочитайте и проверьте все поля ниже.",
'changePasswordFormProgressDialogTitle':	"Изменение учетной записи",
'changePasswordFormProgressDialogConnectedMessageTitle':	"Соединено",
'changePasswordFormProgressDialogConnectedMessageText':	"Выполнено",
'changePasswordFormProgressDialogErrorMessageTitle':	"Ошибка",
'changePasswordFormProgressDialogErrorMessageText':	"Ошибка изменения учетной записи!",
'changeCredentialsPanelEncryptingDataMessageTitle':	"Изменение ключевой фразы",
'changeCredentialsPanelEncryptingDataMessageText':	"Шифрование заголовков карточек",
'changeCredentialsPanelCreatingNewCredentialsMessageTitle':	"Изменение ключевой фразы",
'changeCredentialsPanelCreatingNewCredentialsMessageText':	"Обновление учетной записи",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageTitle':	"Изменение ключевой фразы",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageText':	"Загрузка данных учетной записи в Clipperz",
'changeCredentialsPanelDoneMessageTitle':	"Изменение ключевой фразы",
'changeCredentialsPanelDoneMessageText':	"Выполнено",
'manageOTPTabLabel':	"Управление одноразовыми ключевыми фразами",
'manageOTPTabTitle':	"Управление одноразовыми ключевыми фразами",
'manageOTPTabDescription':	"<p>Одноразовый пароль работает, как Ваша обычная ключевая фраза, но может быть использована только один раз.</p> <p>Если один и тот же пароль будет использоваться снова на следующих этапах, она будет отклонен и процедура входа завершится неудачно.</p> <p>Сразу после входа одноразовый пароль будет удален, чтобы предовратить любую несанкционированную попытку доступа.</p> <p>Одноразовые пароли - удачный выбор для тех, кто обеспокоен кейлоггерами или spyware, которые могут собирать информ.</p> <p> <b>Строго рекомендуется использовать одноразовые пароли для доступа к Clipperz с чужих компьютеров, из интернет-кафе и библиотек.</b> </p> ",
'oneTimePasswordReadOnlyMessage':	"<h6>Извините!</h6> <p>Вы не можете управлять одноразовыми ключевыми фразами в оффлайновой версии Clipperz.</p> ",
'oneTimePasswordLoadingMessage':	"<h6>Загрузка данных</h6> <p>Подождите, пожайлуста ...</p> ",
'oneTimePasswordNoPasswordAvailable':	"<h6>Нет свободных для использования одноразовых ключевых фраз.</h6> <p>Нажмите кнопку “Новая”, чтобы добавить еще одноразовые ключевые фразы в аккаунт.</p> ",
'createNewOTPButtonLabel':	"новая",
'deleteOTPButtonLabel':	"удалить",
'printOTPButtonLabel':	"печать",
'disabledOneTimePassword_warning':	"запрещено",
'oneTimePasswordSelectionLink_selectLabel':	"Выбрать:",
'oneTimePasswordSelectionLink_all':	"все",
'oneTimePasswordSelectionLink_none':	"ни одного",
'oneTimePasswordSelectionLink_used':	"использованные",
'oneTimePasswordSelectionLink_unused':	"неиспользованные",
'saveOTP_encryptUserDataTitle':	"Сохранение одноразовых ключевых фраз",
'saveOTP_encryptUserDataText':	"Обработка новых данных учетной записи ...",
'saveOTP_encryptOTPDataTitle':	"одноразовыми ключевыми фразами",
'saveOTP_encryptOTPDataText':	"Шифрование аутентификационных данных ...",
'saveOTP_sendingDataTitle':	"одноразовыми ключевыми фразами",
'saveOTP_sendingDataText':	"Передача аутентификационных данных на сервер ...",
'saveOTP_updatingInterfaceTitle':	"одноразовыми ключевыми фразами",
'saveOTP_updatingInterfaceText':	"Обновление интерфейса ...",
'accountPreferencesLabel':	"Настройки",
'accountPreferencesTabTitle':	"Настройки",
'accountPreferencesLanguageTitle':	"Выбор языка",
'accountPreferencesLanguageDescription':	"<p>Выберите Ваш язык из списка.</p> ",
'showDonationReminderPanelTitle':	"Напоминания о пожертвованиях",
'showDonationReminderPanelDescription':	"<p>Показать напоминания о пожертвованиях</p> ",
'saveUserPreferencesFormSubmitLabel':	"Сохранить",
'cancelUserPreferencesFormSubmitLabel':	"Отмена",
'accountPreferencesSavingPanelTitle_Step1':	"Сохранение настроек",
'accountPreferencesSavingPanelText_Step1':	"Шифрование настроек",
'accountPreferencesSavingPanelTitle_Step2':	"Сохранение настроек",
'accountPreferencesSavingPanelText_Step2':	"Передача зашифрованных настроек в Clipperz",
'accountLoginHistoryLabel':	"История входов",
'loginHistoryTabTitle':	"История входов",
'loginHistoryReadOnlyMessage':	"<h6>Извините!</h6> <p>История входов не доступна в оффлайновой версии Clipperz.</p> ",
'loginHistoryLoadingMessage':	"<h6>Загрузка данных</h6> <p>Подождите, пожайлуста ...</p> ",
'loginHistoryLoadedMessage':	"<h6>Десять Ваших последних входов</h6> <p> </p> ",
'loginHistoryIPLabel':	"IP",
'loginHistoryTimeLabel':	"дата",
'loginHistoryCurrentSessionText':	"текущая сессия",
'loginHistoryReloadButtonLabel':	"Обновить историю",
'deleteAccountTabLabel':	"Удалить аккаунт",
'deleteAccountTabTitle':	"Удалить аккаунт",
'deleteAccountFormUsernameLabel':	"имя пользователя",
'deleteAccountFormPassphraseLabel':	"ключевая фраза",
'deleteAccountFormSafetyCheckboxLabel':	"Я понимаю, что все мои данные будут удалены и это действие необратимо.",
'deleteAccountFormSubmitLabel':	"Удалить мой аккаунт",
'deleteAccountFormWrongUsernameWarning':	"Неверное имя пользователя",
'deleteAccountFormWrongPassphraseWarning':	"Неверная ключевая фраза",
'deleteAccountFormSafetyCheckWarning':	"Прочтите и отметьте все поля ниже.",
'accountPanelDeletingAccountPanelConfirmationTitle':	"ВНИМАНИЕ",
'accountPanelDeleteAccountPanelConfirmationText':	"Вы уверены, что хотите удалить аккаунт?",
'accountPanelDeleteAccountPanelConfirmButtonLabel':	"Да",
'accountPanelDeleteAccountPanelDenyButtonLabel':	"Нет",
'offlineCopyTabLabel':	"Оффлайновая копия",
'offlineCopyTabTitle':	"Оффлайновая копия",
'offlineCopyTabDescription':	"<p>Одним кликом Вы можете сохранить все зашифрованные данные с серверов Clipperz на жесткий диск и создать оффлайновую версию, которую будете использовать при отсутствии подключения к Интернету.</p> <p>Версия только для чтения безопасна также, как и полная, и не подвергает Ваши данные большим рискам, так как использует тот же код и архитектуру.</p> <ol> <li> <p>Нажмите на ссылку, чтобы начать скачивание.</p> </li> <li> <p>Браузер спросит, что сделать с файлом “Clipperz_YYYYMMDD.html”. Сохраните его на Ваш жесткий диск.</p> </li> <li> <p>Double click on the downloaded file to launch the offline version in your browser.</p> </li> <li> <p>Как обычно, введите имя пользователя и ключевую фразу.</p> </li> </ol> ",
'offlineCopyDownloadLinkLabel':	"Скачать",
'offlineCopyDownloadWarning':	"<h4> <a href=\"#\" id=\"offlineCopyDownloadWarningLink\">Обновите Вашу “оффлайновую копию”!</a> </h4> <p>Вы недавно создали или изменили одну или более карточек: было бы разумным скачать новую оффлайновую копию.</p> ",
'sharingTabLabel':	"Совместное использование",
'sharingTabTitle':	"Совместное использование",
'sharingTabDescription':	"<p>Достаточно часто конфидециальную информацию нужно открыть одному или нескольким людям.</p> <p>Это может быть просто, как дать коллеге ключ доступа к Вашей голосовой почте, когда Вас нет в офисе, или сложно, как открыть доступ наследникам к Вашему счету в местном банке, когда Вы скончаетесь.</p> <p>Clipperz поможет сделать совместное использование Ваших секретов безопасным и простым процессом.</p> <p> </p> <p> <b>Скоро ...</b> </p> ",
'importTabLabel':	"Импорт",
'importTabTitle':	"Импорт",
'importTabDescription':	"<p> <b>Скоро ...</b> </p> ",
'printingTabLabel':	"Экспорт",
'printingTabTitle':	"Экспорт",
'printingTabDescription':	"<p> <b>Печать Ваших данных</b> </p> <p>Нажмите по ссылке, чтобы открыть новое окно со всеми Вашими карточками для печати.</p> <p>Если вы собираетесь распечатать в резервных целях, пожайлуста, рассмотрите более безопасный вариант, как создание “оффлайновой копии”.</p> ",
'printingLinkLabel':	"Версия для печати",
'contactsTabLabel':	"Контакты",
'contactsTabTitle':	"Контакты",
'passwordGeneratorTabLabel':	"Генератор паролей",
'passwordGeneratorTabTitle':	"Генератор паролей",
'passwordGeneratorTabButtonLabel':	"Генератор паролей",
'bookmarkletTabLabel':	"Закладка",
'bookmarkletTabTitle':	"Закладка",
'bookmarkletTabDescription':	"<p>Закладка - это простой инструмент, который может решать очень полезные задачи. Ее можно сохранить и использовать как обычную веб-страницу.</p> <p>Закладки помогут Вам быстро создать новые карточки и новые логины внутри существующих карточек.</p> <p> <b>Пожайлуста, учтите, что закладки действительно не включают какой-либо информации, связанной с аккаунтом (например, имя или ключевая фраза), закладки содержат один и тот же код для каждого пользователя.</b> </p> <h3>Как установить закладку</h3> <h5>Firefox, Camino, Opera, Safari</h5> <ol> <li> <p>Убедитесь, что панель закладок отображается выбором “View > Toolbars > Bookmarks” или похожими пунктами из меню браузера.</p> </li> <li> <p>Нажмите и перетащите ссылку “Добавить в Clipperz” на панель закладок.</p> </li> </ol> <h5>Internet Explorer</h5> <ol> <li> <p>Убедитесь, что отображается панель “Ссылки” выбором “View > Toolbars > Links” из меню браузера.</p> </li> <li> <p>Нажмите правой кнопкой на ссылку “Добавить в Clipperz”.</p> </li> <li> <p>Выберите “Add to favorites” из контекстного меню.</p> </li> <li> <p>Нажмите “Yes” для любых сообщений, которые появятся.</p> </li> <li> <p>Откройте папку “Links” и нажмите “OK”.</p> </li> </ol> ",
'bookmarkletTabBookmarkletTitle':	"Добавить в Clipperz",
'bookmarkletTabInstructions':	"<h3>Как создать новую карточку с ссылками “прямого подключения” в онлайновый сервис</h3> <ol> <li> <p>Откройте веб-страницу с формой входа. (обычно на этой страницы Вы вводите данные вашей учетной записи)</p> </li> <li> <p>Запустите закладку, нажав на нее: появится всплывающее окно.</p> </li> <li> <p>Скопируйте в буфер обмена содержимое текстового поля из всплывающего окна. (ctrl-C)</p> </li> <li> <p>Ввойдите в Ваш аккаунт и нажмите “Добавить новую карточку”.</p> </li> <li> <p>Выберите шаблон “Прямого подключения” и вставьте в текстовое поле содержимое буфера обмена. (ctrl-V)</p> </li> <li> <p>Нажмите кнопку “Создать”, проверьте правильность и нажмите “Сохранить”.</p> </li> </ol> <h3>Как создать ссылку “Прямого подключения” в существующей карточке</h3> <ol> <li> <p>Тоже самое, как и выше.</p> </li> <li> <p>Тоже самое, как и выше.</p> </li> <li> <p>Тоже самое, как и выше.</p> </li> <li> <p>Ввойдите в Ваш аккаунт и выберите карточку с данными учетной записи для только что посещенного веб-сервиса и нажмите “Редактировать”.</p> </li> <li> <p>Вставьте содержимое буфера обмена в текстовое поле в разделе “Прямого подключения”. (ctrl-V)</p> </li> <li> <p>Нажмите “Добавить новое прямое подключение”, проверьте правильность и нажмите “Сохранить”.</p> </li> </ol> <p> </p> <p>Подробнее о закладках <a href=\"http://www.clipperz.com/support/user_guide/bookmarklet\" target=\"_blank\">здесь</a>.</p> ",
'mainPanelDirectLoginBlockLabel':	"Прямые подключения",
'directLinkReferenceShowButtonLabel':	"показать",
'mainPanelDirectLoginBlockDescription':	"<p>Добавьте “Прямые подключения”, чтобы срау входить в веб-сервисы без ввода имени и пароля!</p> <p>“Прямые подключения” значительно усиливают безопасность, так как:</p> <ul> <li> <p>удобно принимать и вводить сложные пароли;</p> </li> <li> <p>никогда не надо использовать простой и один и тот же пароль.</p> </li> </ul> <p>Простая и быстрая конфигурация с помощью закладок.</p> <a href=\"http://www.clipperz.com/support/user_guide/direct_logins\" target=\"_blank\">Подробнее о прямых подключениях</a> ",
'mainPanelRecordsBlockLabel':	"Карточки",
'mainPanelAddRecordButtonLabel':	"Добавить новую карточку",
'mainPanelRemoveRecordButtonLabel':	"Удалить карточку",
'mainPanelRecordFilterBlockAllLabel':	"все",
'mainPanelRecordFilterBlockTagsLabel':	"теги",
'mainPanelRecordFilterBlockSearchLabel':	"поиск",
'recordDetailNoRecordAtAllTitle':	"Добро пожаловать в Clipperz!",
'recordDetailNoRecordAtAllDescription':	"<h5>Начните, добавив карточку.</h5> <p>Карточки - это простой и гибкий инструмент, с помощью которого Вы можете хранить пароли и любую другую информацию.</p> <p>Карточки могут содержать учетные записи для доступа к веб-сайтам, код для замка от велосипеда, данные кредитной карточки, ...</p> <h5>Не забывай о закладках!</h5> <p>Перед началом работы установите закладку “Добавить в Clipperz”: создание карточек будет простым и забавным.</p> <p>Перейдите на панель закладок, чтобы изучить, как установить и использовать их.</p> <p> </p> <a href=\"http://www.clipperz.com/support/user_guide/managing_cards\" target=\"_blank\">Подробнее об создании и управлениями закладками</a> ",
'newRecordWizardTitleBox':	"<h5>Пожайлуста, выберите шаблон</h5> <p>Карточки - это простой и гибкий инструмент, с помощью которого Вы можете хранить пароли и любую другую информацию.</p> <p>Выберите один из шаблонов. Вы всегда сможете настроить ваши карточки, добавляя или удаляя поля.</p> ",
'newRecordWizardBookmarkletConfigurationTitle':	"Прямое подключение",
'newRecordWizardBookmarkletConfigurationDescription':	"<p>Вставьте конфигурационный код, сгенерированный с помощью закладки</p> <p>Будет создана новая карточка с поддержкой прямого подключения.</p> ",
'newRecordWizardCreateButtonLabel':	"Создать",
'newRecordWizardCancelButtonLabel':	"Отмена",
'donateSplashPanelTitle':	"Поддержите Clipperz, сделайте пожертвование сегодня!",
'donateSplashPanelDescription':	"<p>Несколько причин сделать пожертвование:</p> <ul> <li> <p>поддержка развития новых функций</p> </li> <li> <p>оставить Clipperz бесплатным</p> </li> <li> <p>показать признательность нашей упорной работе</p> </li> </ul> <p>Для дополнительной информации посетите нашу <a href=\"http://www.clipperz.com/donations\" target=\"_blank\">страницу пожертвований</a>.</p> <p> <b>Готовы пожертвовать?</b> </p> ",
'donateCloseButtonLabel':	"Еще нет",
'donateDonateButtonLabel':	"Да",
	'recordTemplates':	{
		'WebAccount':	{
			'title':	"Интернет Пароль",
			'description':	"Простая форма для хранения учетной записи в онлайновый сервис."
		},
		'BankAccount':	{
			'title':	"Банковский аккаунт",
			'description':	"Безопасное хранение номера Вашей банковской карты и учетной записи для онлайнового банкинга."
		},
		'CreditCard':	{
			'title':	"Кредитная карта",
			'description':	"Номер карты, срок действия, CCV2 и ПИН всегда в Ваших руках."
		},
		'AddressBookEntry':	{
			'title':	"Запись адресной книги",
			'description':	"Clipperz может также работать, как новая частная адресная книга. Используйте этот шаблон, чтобы легко добавить новую запись."
		},
		'Custom':	{
			'title':	"Пользовательская карточка",
			'description':	"Не важно, какие данные нужно защитить, просто создайте карточку."
		}
	},
	'recordFieldTypologies':	{
		'TXT':	{
			'description':	"simple text field",
			'shortDescription':	"текст"
		},
		'PWD':	{
			'description':	"simple text field, with default status set to hidden",
			'shortDescription':	"пароль"
		},
		'URL':	{
			'description':	"simple text field in edit mode, that became an active url in view mode",
			'shortDescription':	"веб-адрес"
		},
		'DATE':	{
			'description':	"a value set with a calendar helper",
			'shortDescription':	"дата"
		},
		'ADDR':	{
			'description':	"just like the URL, but the active link points to Google Maps (or similar service) passing the address value as argument",
			'shortDescription':	"почтовый адрес"
		},
		'CHECK':	{
			'description':	"check description",
			'shortDescription':	"check"
		},
		'RADIO':	{
			'description':	"radio description",
			'shortDescription':	"radio"
		},
		'SELECT':	{
			'description':	"select description",
			'shortDescription':	"select"
		}
	},
'newRecordPanelGeneralExceptionTitle':	"Ошибка",
'newRecordPanelGeneralExceptionMessage':	"Конфигурационный текст неверен. Убедитесь, что Вы взяли его из окна закладки и попробуйте снова.",
'newRecordPanelWrongBookmarkletVersionExceptionTitle':	"Ошибка",
'newRecordPanelWrongBookmarkletVersionExceptionMessage':	"Конфигурационный текст был сгенерирован с помощью старой весии закладок. Пожайлуста, обновите Вашу закладку и попробуйте снова.",
'newRecordPanelExceptionPanelCloseButtonLabel':	"Отмена",
'mainPanelDeletingRecordPanelConfirmationTitle':	"Удаление выбранной карточки",
'mainPanelDeleteRecordPanelConfirmationText':	"Вы действительно хотите удалить эту карточку?",
'mainPanelDeleteRecordPanelConfirmButtonLabel':	"Ага",
'mainPanelDeleteRecordPanelDenyButtonLabel':	"Не-а",
'mainPanelDeletingRecordPanelInitialTitle':	"Удаление выбранной карточки",
'mainPanelDeletingRecordPanelCompletedText':	"Выполнено",
'deleteRecordPanelCollectRecordDataMessageTitle':	"Удаление карточки",
'deleteRecordPanelCollectRecordDataMessageText':	"Обновление списка карточек",
'deleteRecordPanelEncryptUserDataMessageTitle':	"Удаление карточки",
'deleteRecordPanelEncryptUserDataMessageText':	"Шифрование заголовков карточек",
'deleteRecordPanelSendingDataToTheServerMessageTitle':	"Удаление карточки",
'deleteRecordPanelSendingDataToTheServerMessageText':	"Передача зашифрованных заголовков карчточек в Clipperz",
'deleteRecordPanelUpdatingTheInterfaceMessageTitle':	"Удаление карточки",
'deleteRecordPanelUpdatingTheInterfaceMessageText':	"Обновление интерфейса",
'recordDetailNoRecordSelectedTitle':	"Не выбрана карточка",
'recordDetailNoRecordSelectedDescription':	"<p>Пожайлуста, выберите карточку из списка слева.</p> ",
'recordDetailLoadingRecordMessage':	"Загрузка зашифрованных карточек из Clipperz",
'recordDetailDecryptingRecordMessage':	"Расшифровка данных карточек",
'recordDetailLoadingRecordVersionMessage':	"Загрузка последней версии карточкиn",
'recordDetailDecryptingRecordVersionMessage':	"Расшифровка",
'recordDetailLoadingErrorMessageTitle':	"Ошибка при загрузку",
'recordDetailNotesLabel':	"Примечания",
'recordDetailLabelFieldColumnLabel':	"Метка поля",
'recordDetailDataFieldColumnLabel':	"Данные поля",
'recordDetailTypeFieldColumnLabel':	"Тип",
'recordDetailSavingChangesMessagePanelInitialTitle':	"Сохранение карточки",
'recordDetailAddFieldButtonLabel':	"Добавить новое поле",
'recordDetailPasswordFieldHelpLabel':	"чтобы скопировать пароль в буфер обмена, нажмите на звездочку, затем Ctrl-C",
'recordDetailPasswordFieldScrambleLabel':	"спрятать",
'recordDetailPasswordFieldUnscrambleLabel':	"показать",
'recordDetailDirectLoginBlockTitle':	"Прямые подключения",
'recordDetailNewDirectLoginDescription':	"<p>Настройка прямых подключений</p> ",
'recordDetailDirectLoginBlockNoDirectLoginConfiguredDescription':	"<p>В этой карточке есть данные для доступа в онлайновый сервис?</p> <p>Используйте закладки, чтобы настроить “прямые подключения”!</p> ",
'recordDetailAddNewDirectLoginButtonLabel':	"Добавить новое прямое подключение",
'recordDetailEditButtonLabel':	"Редактировать",
'recordDetailSaveButtonLabel':	"Сохранить",
'recordDetailCancelButtonLabel':	"Отмена",
'newRecordTitleLabel':	"_новую карточку_",
'recordSaveChangesPanelCollectRecordInfoMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelCollectRecordInfoMessageText':	"Обновление заголовков карточек",
'recordSaveChangesPanelEncryptUserDataMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelEncryptUserDataMessageText':	"Шифрование заголовков карточки",
'recordSaveChangesPanelEncryptRecordDataMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelEncryptRecordDataMessageText':	"Шифровани данных карточки",
'recordSaveChangesPanelEncryptRecordVersionDataMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelEncryptRecordVersionDataMessageText':	"Шифрование данных версии карточки",
'recordSaveChangesPanelSendingDataToTheServerMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelSendingDataToTheServerMessageText':	"Передача зашифрованного заголовка карточки в Clipperz",
'recordSaveChangesPanelUpdatingTheInterfaceMessageTitle':	"Сохранение карточки",
'recordSaveChangesPanelUpdatingTheInterfaceMessageText':	"Обновление интерфейса",
'passwordGeneratorPanelTitle':	"Генератор паролей",
'passwordGeneratorPanelOkLabel':	"OK",
'passwordGeneratorPanelCancelLabel':	"Отмена",
'passwordGeneratorLengthLabel':	"длина:",
//'DWRUtilLoadingMessage':	"Загрузка данных ...",
'comingSoon':	"вскоре ...",
'panelCollectingEntryopyMessageText':	"Определение энтропии",
'directLoginConfigurationCheckBoxFieldSelectedValue':	"Да",
'directLoginConfigurationCheckBoxFieldNotSelectedValue':	"Нет",
'WELCOME_BACK':	"Добро пожаловать снова!",
'currentConnectionText':	"Сейчас вы подключились с ip&nbsp;__ip__, очевидно __country__, используя __browser__ на __operatingSystem__.",
'latestConnectionText':	"Последнее соединение было __elapsedTimeDescription__ (__time__) с ip&nbsp;__ip__, очевидно __country__, используя __browser__ на __operatingSystem__.",
'fullLoginHistoryLinkLabel':	"показать полную историю входов",
'elapsedTimeDescriptions':	{
	'MORE_THAN_A_MONTH_AGO':	"за месяц",
	'MORE_THAN_A_WEEK_AGO':	"за неделю",
	'MORE_THAN_*_WEEKS_AGO':	"за несколько __elapsed__ недель",
	'YESTERDAY':	"вчера",
	'*_DAYS_AGO':	"__elapsed__ дней(-я)",
	'ABOUT_AN_HOUR_AGO':	"за час",
	'*_HOURS_AGO':	"__elapsed__ часов(-а)",
	'JUST_A_FEW_MINUTES_AGO':	"несколько минут",
	'ABOUT_*_MINUTES_AGO':	"около __elapsed__ минут"
},
'unknown_ip':	"неизвестный",
'calendarStrings':	{
	'months':	{
		'0':	"Январь",
		'1':	"Февраль",
		'2':	"Март",
		'3':	"Апрель",
		'4':	"Май",
		'5':	"Июнь",
		'6':	"Июль",
		'7':	"Август",
		'8':	"Сентябрь",
		'9':	"Октябрь",
		'10':	"Ноябрь",
		'11':	"Декабрь"
	},
	'shortMonths':	{
		'0':	"Янв",
		'1':	"Фев",
		'2':	"Мар",
		'3':	"Апр",
		'4':	"Май",
		'5':	"Июн",
		'6':	"Июл",
		'7':	"Авг",
		'8':	"Сен",
		'9':	"Окт",
		'10':	"Ноя",
		'11':	"Дек"
	},
	'days':	{
		'0':	"Воскресенье",
		'1':	"Понедельник",
		'2':	"Вторник",
		'3':	"Среда",
		'4':	"Четверг",
		'5':	"Пятница",
		'6':	"Суббота"
	},
	'shortDays':	{
		'0':	"Вск",
		'1':	"Пон",
		'2':	"Втр",
		'3':	"Сре",
		'4':	"Чет",
		'5':	"Пят",
		'6':	"Суб"
	},
	'amDesignation':	"am",
	'pmDesignation':	"pm"
},

__syntaxFix__: "syntax fix"
});
