/*

Copyright 2008-2015 Clipperz Srl

This file is part of Clipperz, the online password manager.
For further information about its features and functionalities please
refer to http://www.clipperz.com.

* Clipperz is free software: you can redistribute it and/or modify it
  under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version.

* Clipperz is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Affero General Public License for more details.

* You should have received a copy of the GNU Affero General Public
  License along with Clipperz. If not, see http://www.gnu.org/licenses/.

*/

Clipperz.PM.Strings.Languages['es-ES'.toLowerCase()] = MochiKit.Base.merge(Clipperz.PM.Strings.Languages['en-us'], {
'clipperzServiceDescription':	"<h2>Guárdelo usted mismo!</h2> <ul> <li> <h3>Clipperz es:</h3> <ul> <li> <p>un simple y seguro administrador de contraseñas</p> </li> <li> <p>una efectiva y simple solución de logueo</p> </li> <li> <p>un maletín digital para sus datos confidenciales</p> </li> </ul> </li> <li> <h3>Con Clipperz usted puede:</h3> <ul> <li> <p>administrar y almacenar en línea sus contraseñas y credenciales digitales</p> </li> <li> <p>ingresar en sus servicios  web  sin ningún nombre de usuario o contraseña</p> </li> <li> <p>protejer todos sus datos sensibles: códigos de alarmas, PINs y números de tarjetas de crédito, &hellip;</p> </li> <li> <p>compartir secretos con sus familiares y socios</p> </li> </ul> </li> <li> <h3>Beneficios de Clipperz:</h3> <ul> <li> <p>es gratis y completamente anónimo</p> </li> <li> <p>con acceso en cualquier momento y desde cualquier ordenador</p> </li> <li> <p>no necesita instalar o descargar ningún programa</p> </li> <li> <p>no necesita guardar secretos en papel o en el ordenador</p> </li> </ul> </li> <li> <h3>Seguridad de Clipperz:</h3> <ul> <li> <p>sus secretos son localmente encriptados por su navegador antes de ser almacenados en  Clipperz</p> </li> <li> <p>la llave de encriptación es una frase clave conocida solo por usted</p> </li> <li> <p>Clipperz almacena sus datos de manera encriptada y nunca accede a ellos en forma de texto plano</p> </li> <li> <p>Clipperz esta basado en esquemas estándares de encriptación, no hemos inventado nada</p> </li> <li> <p>usted puede revisar el código todas las veces que lo desee, ¡ pero no necesita conocer algo de encriptación para ser un usuario feliz!</p> </li> </ul> </li> <li> <a href=\"http://www.clipperz.com\" target=\"_blank\">Aprender más</a> </li> </ul> ",
'loginFormTitle':	"ingrese con su usuario Clipperz",
'loginFormUsernameLabel':	"usuario",
'loginFormPassphraseLabel':	"frase clave",
'loginFormDontHaveAnAccountLabel':	"¿no tiene una cuenta?",
'loginFormCreateOneLabel':	"crear una",
'loginFormForgotYourCredentialsLabel':	"¿perdió sus credenciales?",
'loginFormAarghThatsBadLabel':	"¡Ahhh! ¡eso es malo!",
'loginFormAfraidOfMaliciousScriptsLabel':	"¿evitar scripts maliciosos?",
'loginFormVerifyTheCodeLabel':	"verificar el código",
'loginFormButtonLabel':	"Ingresar",
'loginFormOneTimePasswordCheckboxLabel':	"usar una frase clave desechable",
'loginPanelSwithLanguageDescription':	"<h5>Cambiar a su lenguaje preferido</h5> ",
'browserCompatibilityDescription':	"<p>Obtenga una mejor y más segura experiencia con Firefox. De todas maneras Clipperz funciona también con Opera y MS Explorer!</p> ",
'OTPloginMessagePanelInitialTitle':	"Ingresar usando una frase clave desechable",
'OTPloginMessagePanelInitialText':	"Enviando credenciales OTP ...",
'OTPloginMessagePanelLoadingTitle':	"Ingresar usando una frase clave desechable",
'OTPloginMessagePanelLoadingText':	"Descargando datos de autenticación encriptados desde el servidor ...",
'OTPloginMessagePanelProcessingTitle':	"Ingresar usando una frase clave desechable",
'OTPloginMessagePanelProcessingText':	"Desencriptación local de datos de autenticación ...",
'loginMessagePanelInitialTitle':	"Ingresando ...",
'loginMessagePanelInitialButtonLabel':	"Cancelar",
'loginMessagePanelConnectedTitle':	"Conectado",
'loginMessagePanelConnectedText':	"Hecho",
'loginMessagePanelFailureTitle':	"Error",
'loginMessagePanelFailureText':	"Ingreso fallido",
'loginMessagePanelFailureButtonLabel':	"Cerrar",
'connectionLoginSendingCredentialsMessageTitle':	"Verificando credenciales",
'connectionLoginSendingCredentialsMessageText':	"Enviando credenciales",
'connectionLoginCredentialsVerificationMessageTitle':	"Verificando credenciales",
'connectionLoginCredentialsVerificationMessageText':	"Realizando una autenticación SRP",
'connectionLoginDoneMessageTitle':	"Verificando credenciales",
'connectionLoginDoneMessageText':	"Conectado",
'userLoginPanelUpgradingUserCredentialsMessageTitle':	"Verificando credenciales",
'userLoginPanelUpgradingUserCredentialsMessageText':	"Actualizando sus credenciales al nuevo esquema de autenticación",
'userLoginPanelConnectedMessageTitle':	"Usuario autenticado",
'userLoginPanelConnectedMessageText':	"Exitosamente logueado",
'userLoginPanelTryingAnOlderConnectionSchemaMessageTitle':	"Verifying credentials",
'userLoginPanelTryingAnOlderConnectionSchemaMessageText':	"Probando un esquema de autenticación antiguo",
'userLoginPanelLoadingUserDataMessageTitle':	"Usuario autenticado",
'userLoginPanelLoadingUserDataMessageText':	"Descargando encabezamientos encriptados desde Clipperz",
'userLoginPanelDecryptingUserDataMessageTitle':	"Usuario autenticado",
'userLoginPanelDecryptingUserDataMessageText':	"Desencriptación local de datos",
'userLoginPanelDecryptingUserStatisticsMessageTitle':	"Usuario autenticado",
'userLoginPanelDecryptingUserStatisticsMessageText':	"Desencriptación local de estadísticas de uso",
'splashAlertTitle':	"¡Bienvenido a Clipperz!",
'splashAlertText':	"<p>Algunas advertencias sobre seguridad</p> <ul> <li> <p>Almacenar sus datos en Clipperz es tan seguro como la frase clave que usted elija para protegerlos. Nadie puede acceder a ellos a no ser que conozca la frase clave.</p> </li> <li> <p>Si usted va a usar Clipperz para guardar información sensible y crítica, esté seguro de elegir una frase clave fuerte. ¡Cuanto más larga mejor!</p> </li> <li> <p>Clipperz no le permitirá recuperar una frase clave perdida.</p> </li> </ul> <p>Si necesita más información, por favor visite  el sitio de <a href=\"http://www.clipperz.com\" target=\"_blank\">Clipperz</a>.</p> ",
'splashAlertCloseButtonLabel':	"Aceptar",
'registrationFormTitle':	"Abrir su cuenta",
'registrationFormUsernameLabel':	"usuario",
'registrationFormPassphraseLabel':	"frase clave",
'registrationFormRetypePassphraseLabel':	"reingrese la frase clave",
'registrationFormSafetyCheckLabel':	"Yo entiendo que Clipperz no me permite recuperar frases clave perdidas",
'registrationFormTermsOfServiceCheckLabel':	"He leído y estoy de acuerdo con los <a href='https://www.clipperz.com/terms_service' target='_blank'>Términos de Servicio</a>.",
'registrationFormDoYouAlreadyHaveAnAccountLabel':	"¿usted ya tiene una cuenta?",
'registrationFormSimplyLoginLabel':	"ingreso simple",
'registrationFormButtonLabel':	"Registrarse",
'registrationFormWarningMessageNotMatchingPassphrases':	"Su frase clave no coincide, por favor reescríbala.",
'registrationFormWarningMessageSafetyCheckNotSelected':	"Por favor, lea y chequee todas las casillas debajo.",
'registrationFormWarningMessageTermsOfServiceCheckNotSelected':	"Usted necesita estar de acuerdo con los Términos de Servicio.",
'registrationMessagePanelInitialTitle':	"Creando cuenta ...",
'registrationMessagePanelInitialButtonLabel':	"Cancelar",
'registrationMessagePanelRegistrationDoneTitle':	"Registración",
'registrationMessagePanelRegistrationDoneText':	"Hecho",
'registrationMessagePanelFailureTitle':	"Registración fallada",
'registrationMessagePanelFailureButtonLabel':	"Cerrar",
'connectionRegistrationSendingRequestMessageText':	"Verificando credenciales",
'connectionRegistrationSendingCredentialsMessageText':	"Enviando credenciales",
'registrationSplashPanelTitle':	"Aviso de seguridad",
'registrationSplashPanelDescriptionConfig':	"<p>Estas son sus credenciales de Clipperz, cuídelas. ¡Clipperz nunca más le mostrará su cuenta y frase clave por segunda vez!</p> ",
'registrationSplashPanelUsernameLabel':	"usuario",
'registrationSplashPanelPassphraseLabel':	"frase clave",
'registrationSplashPanelShowPassphraseButtonLabel':	" mostrar frase clave",
'donateHeaderLinkLabel':	"donaciones",
'creditsHeaderLinkLabel':	"créditos",
'feedbackHeaderLinkLabel':	"contacto",
'helpHeaderLinkLabel':	"ayuda",
'forumHeaderLinkLabel':	"foro",
'recordMenuLabel':	"tarjetas",
'accountMenuLabel':	"cuenta",
'dataMenuLabel':	"datos",
'contactsMenuLabel':	"contactos",
'toolsMenuLabel':	"herramientas",
'logoutMenuLabel':	"salir",
'lockMenuLabel':	"bloquear",
'lockTitle':	"La cuenta está bloqueada",
'lockDescriptionConfig':	"<p>Para desbloquear su cuenta, por favor ingrese su frase clave</p> ",
'unlockButtonLabel':	"desbloquear",
'changePasswordTabLabel':	"Cambiar su frase clave",
'changePasswordTabTitle':	"Cambiar su frase clave",
'changePasswordFormUsernameLabel':	"usuario",
'changePasswordFormOldPassphraseLabel':	"frase clave anterior",
'changePasswordFormNewPassphraseLabel':	"nueva frase clave",
'changePasswordFormRetypePassphraseLabel':	"reingrese su nueva frase clave",
'changePasswordFormSafetyCheckboxLabel':	"Yo entiendo que Clipperz no me permite recuperar una frase clave perdida.",
'changePasswordFormSubmitLabel':	"Cambiar",
'changePasswordFormWrongUsernameWarning':	"Usuario incorrecto",
'changePasswordFormWrongPassphraseWarning':	"Frase clave incorrecta",
'changePasswordFormWrongRetypePassphraseWarning':	"Sus frases claves no coinciden, por favor reescríbalas.",
'changePasswordFormSafetyCheckWarning':	"Por favor lea y seleccione la casilla de abajo.",
'changePasswordFormProgressDialogTitle':	"Cambiando credenciales de usuario",
'changePasswordFormProgressDialogConnectedMessageTitle':	"Conectado",
'changePasswordFormProgressDialogConnectedMessageText':	"Hecho",
'changePasswordFormProgressDialogErrorMessageTitle':	"Error",
'changePasswordFormProgressDialogErrorMessageText':	"¡Cambio de credenciales fallado!",
'changeCredentialsPanelEncryptingDataMessageTitle':	"Cambiando su frase clave",
'changeCredentialsPanelEncryptingDataMessageText':	"Encriptación local de encabezados de tarjetas",
'changeCredentialsPanelCreatingNewCredentialsMessageTitle':	"Cambiando su frase clave",
'changeCredentialsPanelCreatingNewCredentialsMessageText':	"Actualizando su credenciales",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageTitle':	"Cambiando su frase clave",
'changeCredentialsPanelSendingNewCredentialsToTheServerMessageText':	"Subiendo sus credenciales encriptadas a Clipperz",
'changeCredentialsPanelDoneMessageTitle':	"Cambiando su frase clave",
'changeCredentialsPanelDoneMessageText':	"Hecho",
'manageOTPTabLabel':	"Administrar su frases clave desechables",
'manageOTPTabTitle':	"Administrar su frases clave desechables",
'manageOTPTabDescription':	"<p>Una frase clave desechable uso funciona como una frase clave regular, pero puede ser usada solo una vez.</p> <p>Si las misma frase clave es usada nuevamente en un segundo intento de acceso, esta será rechazada y el proceso de acceso fallará.</p> <p>Inmediatamente después de un acceso exitoso, su on-time frase clave será borrada previniendo accesos fraudulentos.</p> <p>Frases claves desechables son una excelente elección para protegerse de keyloggers y spywares, que pueden recolectar datos desde máquinas comprometidas.</p> <p> <b>Le recomendamos muy fuertemente que use frases claves desechables uso cuando acceda a Clipperz desde terminales públicas, como Internet Cafés, Cybercafés y bibliotecas.</b> </p> ",
'oneTimePasswordReadOnlyMessage':	"<h6>¡Disculpe!</h6> <p>Usted no puede usar su frases clave desechables mientras usa la versión fuera de línea de Clipperz.</p> ",
'oneTimePasswordLoadingMessage':	"<h6>Cargando datos</h6> <p>Por favor espere ...</p> ",
'oneTimePasswordNoPasswordAvailable':	"<h6>No hay frase clave desechables disponible</h6> <p>Haga click en el botón “Nueva” para agregar una frase clave desechables a su cuenta.</p> ",
'createNewOTPButtonLabel':	"Nueva",
'deleteOTPButtonLabel':	"Borrar",
'printOTPButtonLabel':	"Imprimir",
'disabledOneTimePassword_warning':	"desabilitado",
'oneTimePasswordSelectionLink_selectLabel':	"Seleccionar:",
'oneTimePasswordSelectionLink_all':	"todo",
'oneTimePasswordSelectionLink_none':	"ninguna",
'oneTimePasswordSelectionLink_used':	"usada",
'oneTimePasswordSelectionLink_unused':	"sin uso",
'saveOTP_encryptUserDataTitle':	"Guardando frase clave desechable",
'saveOTP_encryptUserDataText':	"Procesando nuevas credenciales OTP ...",
'saveOTP_encryptOTPDataTitle':	"Guardando frase clave desechable",
'saveOTP_encryptOTPDataText':	"Encriptación local de datos de autenticación ...",
'saveOTP_sendingDataTitle':	"Guardando frase clave desechable",
'saveOTP_sendingDataText':	"Enviando datos de autenticación al servidor ...",
'saveOTP_updatingInterfaceTitle':	"Guardando frase clave desechable",
'saveOTP_updatingInterfaceText':	"Actualizando interface ...",
'accountPreferencesLabel':	"Preferencias",
'accountPreferencesTabTitle':	"Preferencias",
'accountPreferencesLanguageTitle':	"Seleccione el lenguaje",
'accountPreferencesLanguageDescription':	"<p>Elija su lenguaje preferido de la siguiente lista.<p> ",
'showDonationReminderPanelTitle':	"Recordatorios de donaciones",
'showDonationReminderPanelDescription':	"<p>Mostrar recordatorios de donaciones</p> ",
'accountPreferencesInterfaceTitle':	"Personalización de la interface",
'accountPreferencesInterfaceDescription':	"<p>Ajuste Clipperz a sus necesidades.</p> ",
'saveUserPreferencesFormSubmitLabel':	"Guardar",
'cancelUserPreferencesFormSubmitLabel':	"Cancelar",
'accountPreferencesSavingPanelTitle_Step1':	"Guardando preferencias",
'accountPreferencesSavingPanelText_Step1':	"Encriptación local de sus preferencias",
'accountPreferencesSavingPanelTitle_Step2':	"Guardando preferencias",
'accountPreferencesSavingPanelText_Step2':	"Enviando preferencias encriptadas a Clipperz",
'accountLoginHistoryLabel':	"Historial de accesos",
'loginHistoryTabTitle':	"Historial de accesos",
'loginHistoryReadOnlyMessage':	"<h6>¡Perdón!</h6> <p>El historial de acceso no está disponible mientras usa la versión fuera de línea de Clipperz.</p> ",
'loginHistoryLoadingMessage':	"<h6>Cargando datos</h6> <p>Por favor espere ...</p> ",
'loginHistoryLoadedMessage':	"<h6>Sus últimos 10 accesos</h6> <p> </p> ",
'loginHistoryIPLabel':	"IP",
'loginHistoryTimeLabel':	"fecha",
'loginHistoryCurrentSessionText':	"sesión actual",
'loginHistoryReloadButtonLabel':	"Refrescar historial de acceso",
'deleteAccountTabLabel':	"Borrar su cuenta",
'deleteAccountTabTitle':	"Borrar su cuenta",
'deleteAccountFormUsernameLabel':	"usuario",
'deleteAccountFormPassphraseLabel':	"frase clave",
'deleteAccountFormSafetyCheckboxLabel':	"Yo entiendo que todos mis datos serán borrados y que esta acción es irreversible.",
'deleteAccountFormSubmitLabel':	"Borrar mi cuenta",
'deleteAccountFormWrongUsernameWarning':	"Usuario incorrecto",
'deleteAccountFormWrongPassphraseWarning':	"Frase clave incorrecta",
'deleteAccountFormSafetyCheckWarning':	"Por favor, léa y marque la opción debajo.",
'accountPanelDeletingAccountPanelConfirmationTitle':	"ATENCIÓN",
'accountPanelDeleteAccountPanelConfirmationText':	"¿Esta Ud. seguro que desea borrar esta cuenta?",
'accountPanelDeleteAccountPanelConfirmButtonLabel':	"Sí",
'accountPanelDeleteAccountPanelDenyButtonLabel':	"No",
'offlineCopyTabLabel':	"Copia fuera de línea",
'offlineCopyTabTitle':	"Copia fuera de línea",
'offlineCopyTabDescription':	"<p>Con solo un clik usted puede descargar todos sus datos encriptados desde los servidores de Clipperz a su disco rígido y crear una versión solo-lectura fuera de línea para ser usada cuando usted no está conectado a Internet.</p> <p>La versión solo-lectura es tan segura como la lectura-escritura y no expondrá sus datos a mayores riegos desde el momento que ambas comparten el mismo código y arquitectura de seguridad.</p> <ol> <li> <p>Haga click en el link debajo para comenzar la descarga.</p> </li> <li> <p>El navegador le preguntará que hacer con el archivo “Clipperz_YYYYMMDD.html”. Guárdelo en su disco rígido.</p> </li> <li> <p>Haga doble click en el archivo descargado para ejecutar la versión fuera de línea en su navegador.</p> </li> <li> <p>Ingrese el usuario y la frase clave habitual.</p> </li> </ol> ",
'offlineCopyDownloadLinkLabel':	"Descargar",
'offlineCopyDownloadWarning':	"<h4> <a href=\"#\" id=\"offlineCopyDownloadWarningLink\">¡Actualize su “copia fuera de línea”!</a> </h4> <p>Usted ha recientemente creado o modificado una o más tarjetas, podría ser necesario que realize una nueva “copia fuera de línea”.</p> ",
'sharingTabLabel':	"Compartir",
'sharingTabTitle':	"Compartir",
'sharingTabDescription':	"<p>Muy frecuentemente una pieza de información confidencial necesita ser compartida con una o más personas.</p> <p>Esto debería ser tan simple como darle a sus colegas el accese al código de su casilla de voz cuando está fuera de la oficina, o tan complicado con habilitarles a sus herederos el derecho de acceder a su caja de seguridad en su banco.</p> <p>Clipperz puede permitirle compartir sus secretos de una forma segura y directa.</p> <p> </p> <p> <b>Proximamente ...</b> </p> ",
'importTabLabel':	"Importar",
'importTabTitle':	"Importar",
'importTabDescription':	"<p> <b>Proximamente ...</b> </p> ",
'printingTabLabel':	"Exportar",
'printingTabTitle':	"Exportar",
'printingTabDescription':	"<p> <b>Imprima sus datos</b> </p> <p>Haciendo click en el enlace que sigue se abrirá una nueva ventana mostrando todas sus tarjetas en un formato imprimible.</p> <p>Si usted está imprimiendo con propósitos de respaldo, por favor considere la opción más segura provista por la creación de una “copia fuera de línea”.</p> ",
'printingLinkLabel':	"Versión imprimible",
'contactsTabLabel':	"Contactos",
'contactsTabTitle':	"Contactos",
'passwordGeneratorTabLabel':	"Generador de contraseñas",
'passwordGeneratorTabTitle':	"Generador de contraseñas",
'paswordGeneratorTabDescriptionConfig':	"<p> </p> ",
'passwordGeneratorTabButtonLabel':	"Generar contraseña",
'bookmarkletTabLabel':	"Bookmarklet",
'bookmarkletTabTitle':	"Bookmarklet",
'bookmarkletTabDescription':	"<p>Un bookmarklet es una simple herramienta de \"un click\" que puede realizar tareas muy útiles. Este puede ser grabado y usado como un marcador normal de una página web.</p> <p>El Clipperz bookmarklet le ayudará a usted a crear rapidamente tarjetas nuevas y accesos directos dentro de las tarjetas existentes.</p> <p> <b>Por favor tenga en cuenta que el bookmarklet no incluye ninguna información relacionadas con su cuenta (ej: su nombre de usuario o clave), el bookmarklet es una herramienta general que contiene el mismo código para todos los usuarios de Clipperz.</b> </p> <h3>How to install the bookmarklet</h3> <h5>Firefox, Camino, Opera, Safari</h5> <ol> <li> <p>Asegúrese que la “Barra de marcadores” está mostrada seleccionando “Ver > Barra de herramientas > Barra de marcadores”, menú similar, desde el menú del navegador.</p> </li> <li> <p>Arrastre el enlace “Agregar a Clipperz” sobre la barra de marcadores.</p> </li> </ol> <h5>Internet Explorer</h5> <ol> <li> <p>Asegúrese que la barra “Vínculos” es mostrada seleccionando “Ver > Barra de Herramientas > Herramientas > Vínculos” desde el menú del navegador.</p> </li> <li> <p>Haga click con el botón derecho del mouse en el link “Agregar a Clipperz”.</p> </li> <li> <p>Seleccione “Agregar a favoritos” desde el menú contextual.</p> </li> <li> <p>Haga click en “Si” o “Acepto” a cualquier advertencia de seguridad que le aparezca.</p> </li> <li> <p>Abra la carpeta “Vínculos” y haga click en “OK”</p> </li> </ol> ",
'bookmarkletTabBookmarkletTitle':	"Agregar a Clipperz",
'bookmarkletTabInstructions':	"<h3>Como crear una nueva tarjeta que incluya un enlace de “acceso directo” a un servicio en línea.</h3> <ol> <li> <p>Abra una página web dónde el formulario de logueo está almacenado (es la página donde usualmente ingresa sus credenciales firmadas)</p> </li> <li> <p>Ejecute  el bookmarklet haciendo click en éste: una ventana emergente (pop-up) aparecerá sobre la página web.</p> </li> <li> <p>Copie al portapapeles el contenido de todo el texto dentro de la ventana emergente (pop-up) (Ctrl-C)</p> </li> <li> <p>Ingrese en su cuenta Clipperz y haga click en el botón <b>Agregar nueva tarjeta</b>.</p> </li> <li> <p>Seleccione la plantilla “Acceso directo” y pegue el contenido del portapapeles en el formulario (Ctrl-V)</p> </li> <li> <p>Haga click en el botón <b>Crear</b>, revise los datos y luego haga click en <b>Guardar</b>.</p> </li> </ol> <h3>Cómo agregar un enlace “acceso directo” a una tarjeta existente</h3> <ol> <li> <p>Igual que arriba.</p> </li> <li> <p>Igual que arriba.</p> </li> <li> <p>Igual que arriba.</p> </li> <li> <p>Ingrese en su cuenta Clipperz y seleccione una tarjeta conteniendo las credenciales de un servicio web que usted visitó y haga click en el botón <b>Editar</b>.</p> </li> <li> <p>Pegue el contenido del portapapeles en el área de texto de la sección “Acceso directo” (Ctrl-V)</p> </li> <li> <p>Haga click en el botón <b>Agregar acceso directo</b>, revise los detalles y luego haga click en <b>Guardar</b>.</p> </li> </ol> <p> </p> <p>Más información sobre bookmarklet está <a href=\"http://www.clipperz.com/support/user_guide/bookmarklet\" target=\"_blank\">disponible aquí</a>.</p> ",
'mainPanelDirectLoginBlockLabel':	"Accesos directos",
'directLinkReferenceShowButtonLabel':	"ver",
'mainPanelDirectLoginBlockDescription':	"<p>¡ Agregar “accesos directos” para ingresar en sus cuentas de la web sin necesidad de escribir nombres de usuarios o claves!</p> <p>“Accesos directos” incrementa notablemente la seguridad de sus claves desde que ud. puede:</p> <ul> <li> <p>usar claves complejas con comodidad;</p> </li> <li> <p>nunca más reusar la misma clave simple.</p> </li> </ul> <p> </p> <a href=\"http://www.clipperz.com/support/user_guide/direct_logins\" target=\"_blank\">Apreender más sobre “accesos directos”</a> ",
'mainPanelRecordsBlockLabel':	"Tarjetas",
'mainPanelAddRecordButtonLabel':	"Agregar tarjeta nueva",
'mainPanelRemoveRecordButtonLabel':	"Borrar tarjeta",
'mainPanelRecordFilterBlockAllLabel':	"todo",
'mainPanelRecordFilterBlockTagsLabel':	"tags",
'mainPanelRecordFilterBlockSearchLabel':	"buscar",
'recordDetailNoRecordAtAllTitle':	"¡Bienvenido a Clipperz!",
'recordDetailNoRecordAtAllDescription':	"<h5>Comienze agregando tarjetas a su cuenta.</h5> <p>Tarjetas son formularios simples y flexibles donde Usted puede almacenar sus claves y cualquier otro dato confidencial.</p> <p>Tarjetas pueden contener credenciales para acceder a un sitio web, la conbinación del candado de su bicicleta, detalles de su tarjeta de crédito, ....</p> <h5>¡No olvide los bookmarklet!</h5> <p>Antes de comenzar, instale el “Agregar a Clipperz” bookmarklet: esta hará la creación de tarjetas más fácil y más divertida.</p> <p>Vaya al marcador “herramientas” para descubrir como instalar y usarlo.</p> <p> </p> <p>Luego simplemente haga click en el botón “Agregar nueva tarjeta” y disfrute su cuenta Clipperz.</p> <p> </p> <a href=\"http://www.clipperz.com/support/user_guide/managing_cards\" target=\"_blank\">Apreender más acerca de la creación y administración de las tarjetas</a> ",
'newRecordWizardTitleBox':	"<h5>Por favor seleccione una plantilla</h5> <p>Tarjetas son formularios simples y flexibles donde usted puede almacenar claves y cualquier otro dato confidencial.</p> <p>Comienze eligiendo una de las plantillas que se encuentran debajo. Usted siempre puede personalizar sus tarjetas más tarde agregando o borrando campos.</p> ",
'newRecordWizardBookmarkletConfigurationTitle':	"Acceso directo",
'newRecordWizardBookmarkletConfigurationDescription':	"<p>Pegue debajo el código de configuración generado por el bookmarklet Clipperz.</p> <p>Una nueva tarjeta con un acceso directo a su cuenta web será creada.</p> ",
'newRecordWizardCreateButtonLabel':	"Crear",
'newRecordWizardCancelButtonLabel':	"Cancelar",
'donateSplashPanelTitle':	"¡Apoye a Clipperz, haga una donación hoy!",
'donateSplashPanelDescription':	"<p>Una pocas buenas razones para hacer una donación:</p> <ul> <li> <p>apoyar el desarrollo de nuevas utilidades</p> </li> <li> <p>mantener Clipperz gratuito</p> </li> <li> <p>mostrar su aprecio por nuestro duro trabajo</p> </li> </ul> <p>Por cualquier información adicional, por favor visite nuestra <a href=\"http://www.clipperz.com/donations\" target=\"_blank\">página de donaciones</a>.</p> <p> <b>¿Listo para hacer una donación?</b> </p> ",
'donateCloseButtonLabel':	"No todavía",
'donateDonateButtonLabel':	"Si",
'recordTemplates':	{
	'WebAccount':	{
		'title':	"Contraseña web",
		'description':	"<p>Una simple tarjeta para almacenar sus credenciales de acceso a sus servicios online.</p> ",
		'fields':	{
			'URL':	"Dirección web",
			'TXT':	"Usuario o correo  electrónico",
			'PWD':	"Contraseña"
		}
	},
	'BankAccount':	{
		'title':	"Cuenta bancaria",
		'description':	"<p>Almacene en forma segura su número de cuenta bancaria y credenciales de servicios bancarios en línea.</p> ",
		'fields':	{
			'TXT':	"Banco",
			'TXT':	"Número de cuenta",
			'URL':	"Sitio web del Banco",
			'TXT':	"ID del servicio bancario en línea",
			'PWD':	"Contraseña del servicio bancario en línea"
		}
	},
	'CreditCard':	{
		'title':	"Tarjeta de crédito",
		'description':	"<p>Número de tarjeta, fecha de vencimiento, CVV2 y PIN siempre a mano con Clipperz.</p> ",
		'fields':	{
			'TXT':	"Tipo (Visa, AmEx, ...)",
			'TXT':	"Número",
			'TXT':	"Nombre del  propietario",
			'TXT':	"Fecha de vencimiento",
			'TXT':	"CVV2",
			'PWD':	"PIN cajero automático",
			'URL':	"Sitio web tarjeta",
			'TXT':	"Usuario",
			'PWD':	"Contraseña"
		}
	},
	'AddressBookEntry':	{
		'title':	"Libreta de direcciones",
		'description':	"<p>Clipperz puede también funcionar como su nueva libreta privada de direcciones. Use esta plantilla para crear fácilmente nuevas entradas.</p> ",
		'fields':	{
			'TXT':	"Nombre",
			'TXT':	"Correo electrónico",
			'TXT':	"Teléfono",
			'TXT':	"Móvil",
			'ADDR':	"Dirección"
		}
	},
	'Custom':	{
		'title':	" Tarjeta personalizada",
		'description':	"<p>No importa que tipo de dato confidencial usted necesita proteger, puede crear la tarjeta que necesite.</p> ",
		'fields':	{
			'TXT':	"Etiqueta 1",
			'TXT':	"Etiqueta 2",
			'TXT':	"Etiqueta 3"
		}
	}
},
'recordFieldTypologies':	{
	'TXT':	{
		'description':	"simple text field",
		'shortDescription':	"texto"
	},
	'PWD':	{
		'description':	"simple text field, with default status set to hidden",
		'shortDescription':	"contraseña"
	},
	'URL':	{
		'description':	"simple text field in edit mode, that became an active url in view mode",
		'shortDescription':	"dirección web"
	},
	'DATE':	{
		'description':	"a value set with a calendar helper",
		'shortDescription':	"fecha"
	},
	'ADDR':	{
		'description':	"just like the URL, but the active link points to Google Maps (or similar service) passing the address value as argument",
		'shortDescription':	"dirección postal"
	},
	'CHECK':	{
		'description':	"check description",
		'shortDescription':	"check"
	},
	'RADIO':	{
		'description':	"radio description",
		'shortDescription':	"radio"
	},
	'SELECT':	{
		'description':	"select description",
		'shortDescription':	"select"
	}
},
'newRecordPanelGeneralExceptionTitle':	"Error",
'newRecordPanelGeneralExceptionMessage':	"El texto de configuración no es válido. Asegúrese que toma su texto desde la ventana emergente del bookmarklet.",
'newRecordPanelWrongBookmarkletVersionExceptionTitle':	"Error",
'newRecordPanelWrongBookmarkletVersionExceptionMessage':	"El texto de configuración ha sido generado por una versión anterior de bookmarklet. Por favor actualize su bookmarklet y pruebe nuevamente.",
'newRecordPanelExceptionPanelCloseButtonLabel':	"Cancelar",
'mainPanelDeletingRecordPanelConfirmationTitle':	"Eliminando tarjeta seleccionada",
'mainPanelDeleteRecordPanelConfirmationText':	"¿Desea realmente eliminar la tarjeta seleccionada?",
'mainPanelDeleteRecordPanelConfirmButtonLabel':	"Sí",
'mainPanelDeleteRecordPanelDenyButtonLabel':	"No",
'mainPanelDeletingRecordPanelInitialTitle':	"Eliminando tarjeta seleccionada",
'mainPanelDeletingRecordPanelCompletedText':	"Hecho",
'deleteRecordPanelCollectRecordDataMessageTitle':	"Eliminar tarjeta",
'deleteRecordPanelCollectRecordDataMessageText':	"Actualizando lista de tarjetas",
'deleteRecordPanelEncryptUserDataMessageTitle':	"Eliminar tarjeta",
'deleteRecordPanelEncryptUserDataMessageText':	"Encriptación local de encabezamiento de tarjetas",
'deleteRecordPanelSendingDataToTheServerMessageTitle':	"Eliminar tarjeta",
'deleteRecordPanelSendingDataToTheServerMessageText':	"Subiendo encabezamiento de tarjetas encriptadas a Clipperz",
'deleteRecordPanelUpdatingTheInterfaceMessageTitle':	"Eliminar tarjeta",
'deleteRecordPanelUpdatingTheInterfaceMessageText':	"Actualizando interface",
'recordDetailNoRecordSelectedTitle':	"No hay tarjetas seleccionadas",
'recordDetailNoRecordSelectedDescription':	"<p>Por favor seleccione una tarjeta de la lista de la izquierda.</p> ",
'recordDetailLoadingRecordMessage':	"Descargando tarjetas encriptadas desde Clipperz",
'recordDetailDecryptingRecordMessage':	"Desencriptación local de los datos de las tarjetas",
'recordDetailLoadingRecordVersionMessage':	"Descargando última versión de la tarjeta",
'recordDetailDecryptingRecordVersionMessage':	"Desencriptación local de la última versión",
'recordDetailLoadingErrorMessageTitle':	"Error mientras descargaba la tarjeta",
'recordDetailNotesLabel':	"Notas",
'recordDetailLabelFieldColumnLabel':	"Campo título",
'recordDetailDataFieldColumnLabel':	"Campo de datos",
'recordDetailTypeFieldColumnLabel':	"Tipo",
'recordDetailSavingChangesMessagePanelInitialTitle':	"Guardando tarjeta",
'recordDetailAddFieldButtonLabel':	"Agregar nuevo campo",
'recordDetailPasswordFieldHelpLabel':	"para copiar la contraseña al portapapeles, haga click en la estrella y luego Ctrl-C",
'recordDetailPasswordFieldScrambleLabel':	"ocultar",
'recordDetailPasswordFieldUnscrambleLabel':	"mostrar",
'recordDetailDirectLoginBlockTitle':	"Acceso directos",
'recordDetailNewDirectLoginDescription':	"<p>Configuración de los accesos directos</p> ",
'recordDetailDirectLoginBlockNoDirectLoginConfiguredDescription':	"<p>¿Esta tarjeta contiene credenciales para acceder a un servicio en línea?</p> <p>¡Use los bookmarklet para configurar un \"acceso directo\" desde Clpperz con solo un click!</p> ",
'recordDetailAddNewDirectLoginButtonLabel':	"Agregar nuevo acceso directo",
'recordDetailEditButtonLabel':	"Editar",
'recordDetailSaveButtonLabel':	"Guardar",
'recordDetailCancelButtonLabel':	"Cancelar",
'newRecordTitleLabel':	"_nueva tarjeta_",
'recordSaveChangesPanelCollectRecordInfoMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelCollectRecordInfoMessageText':	"Actualizando encabezamiento de tarjetas",
'recordSaveChangesPanelEncryptUserDataMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelEncryptUserDataMessageText':	"Encriptación local de encabezamiento de tarjetas",
'recordSaveChangesPanelEncryptRecordDataMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelEncryptRecordDataMessageText':	"Encriptación local de los datos de la tarjeta",
'recordSaveChangesPanelEncryptRecordVersionDataMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelEncryptRecordVersionDataMessageText':	"Encriptación local de la versión de los datos de la tarjeta",
'recordSaveChangesPanelSendingDataToTheServerMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelSendingDataToTheServerMessageText':	"Subiendo encabezamiento de tarjeta encriptada a Clipperz",
'recordSaveChangesPanelUpdatingTheInterfaceMessageTitle':	"Guardar tarjeta",
'recordSaveChangesPanelUpdatingTheInterfaceMessageText':	"Actualizando la interface",
'passwordGeneratorPanelTitle':	"Generador de contraseñas",
'passwordGeneratorPanelOkLabel':	"Ok",
'passwordGeneratorPanelCancelLabel':	"Cancelar",
'passwordGeneratorLengthLabel':	"longitud:",
//'DWRUtilLoadingMessage':	"Cargando datos ...",
'comingSoon':	"próximamente ...",
'panelCollectingEntryopyMessageText':	"Recogiendo entropía",
'directLoginConfigurationCheckBoxFieldSelectedValue':	"Sí",
'directLoginConfigurationCheckBoxFieldNotSelectedValue':	"No",
'WELCOME_BACK':	"¡Bienvenido!",
'currentConnectionText':	"Usted está ahora conectado desde ip&nbsp;__ip__, aparentemente desde __country__, usando __browser__ en __operatingSystem__.",
'latestConnectionText':	"Su última conexión fue __elapsedTimeDescription__ (__time__) desde ip&nbsp;__ip__, aparentemente desde __country__, usando __browser__ en __operatingSystem__.",
'fullLoginHistoryLinkLabel':	"mostrar historial de acceso",
'elapsedTimeDescriptions':	{
	'MORE_THAN_A_MONTH_AGO':	"más de un mes atrás",
	'MORE_THAN_A_WEEK_AGO':	"más de una semana atrás",
	'MORE_THAN_*_WEEKS_AGO':	"más de __elapsed__ semanas atrás",
	'YESTERDAY':	"ayer",
	'*_DAYS_AGO':	"__elapsed__ días atrás",
	'ABOUT_AN_HOUR_AGO':	"about an hour ago",
	'*_HOURS_AGO':	"__elapsed__ hours ago",
	'JUST_A_FEW_MINUTES_AGO':	"hace unos minutos",
	'ABOUT_*_MINUTES_AGO':	"hace __elapsed__ minutos atrás"
},
'unknown_ip':	"desconocida",
'calendarStrings':	{
	'months':	{
		'0':	"Enero",
		'1':	"Febrero",
		'2':	"Marzo",
		'3':	"Abril",
		'4':	"Mayo",
		'5':	"Junio",
		'6':	"Julio",
		'7':	"Agosto",
		'8':	"Setiembre",
		'9':	"Octubre",
		'10':	"Noviembre",
		'11':	"Diciembre"
	},
	'shortMonths':	{
		'0':	"Ene",
		'1':	"Feb",
		'2':	"Mar",
		'3':	"Abr",
		'4':	"May",
		'5':	"Jun",
		'6':	"Jul",
		'7':	"Ago",
		'8':	"Set",
		'9':	"Oct",
		'10':	"Nov",
		'11':	"Dic"
	},
	'days':	{
		'0':	"Domingo",
		'1':	"Lunes",
		'2':	"Martes",
		'3':	"Miércoles",
		'4':	"Jueves",
		'5':	"Viernes",
		'6':	"Sábado"
	},
	'shortDays':	{
		'0':	"Dom",
		'1':	"Lun",
		'2':	"Mar",
		'3':	"Mie",
		'4':	"Jue",
		'5':	"Vie",
		'6':	"Sab"
	},
	'veryShortDays':	{
		'0':	"Do",
		'1':	"Lu",
		'2':	"Ma",
		'3':	"Mi",
		'4':	"Ju",
		'5':	"Vi",
		'6':	"Sa"
	},
	'amDesignation':	"am",
	'pmDesignation':	"pm"
},

__syntaxFix__: "syntax fix"
});
